param/__init__.py
param/parameterized.py

In response to the recent issue https://github.com/ioam/param/issues/74 and the general annoyance with allow_None being only supported by a few Parameters I've created a SupportsAllowNone baseclass as Jim suggested. Additionally I've added a Tuple parameter as the baseclass for NumericTuple.

Added baseclasses for allow_None and Tuple

---

numbergen/__init__.py

Adds an explicit seed parameter for random number generators. This seed will now also control time-dependent random streams (previously you had to mangle the name with the seed yourself).
I have tested that this works with the updated SOM tutorial (time dependent streams for the input generator)  but I cannot guarantee that this won't break everything else!

Added seed parameter to RandomDistribution number generators

---

param/parameterized.py
tests/testparameterizedrepr.py

This PR adds something I've long wished for in param: sensible, short reprs that actually work. :-)
Although I started implementing this in ``__repr__``,  I saw the note about ``repr`` needing to be fast and then decided against implementing it there once I realized what was required.
Instead of changing ``__repr__``, I've ended up making a more robust ``pprint`` function that can be used as follows:
```python
class Foo(param.Parameterized):
a = param.Number(4, precedence=6)
b = param.String('B', precedence=-9)
c = param.Number(4, precedence=0)
z = param.Number(4, precedence=0)
def __init__(self, a, b, c=4, d=99, **kwargs):
self.d = d
super(Foo, self).__init__(a=a, b=b, c=c, **kwargs)
def __repr__(self):
return param.parameterized.pprint(self, {'d':self.d})
```
First the positional …

Added pprint function to parameterized.py

---

param/parameterized.py

This commit adds unicode support for param.String, which has been requested on multiple occasions, see https://github.com/ioam/param/issues/73 and https://github.com/ioam/holoviews/issues/29. This is the simplest possible fix that will get param to support Unicode strings in Python 2.
To handle unicode correctly consistently we should consider importing: ```from future import unicode_literals``` everywhere, but I'm not sure what the implications of that change would be.
The fully verbose version providing compatibility for all string, bytes and unicode types is the following but that's probably overkill:
```
try:
unicode = unicode
except NameError:
str = str
unicode = str
bytes = bytes
basestring = (str,bytes)
else:
str = str
unicode = unicode
bytes = str
basestring = basestring
```

Unicode support for param.String

---

.travis.yml
setup.cfg
setup.py

This small PR enables cythonizing for the param ``__init__``, ``parameterized`` and ``version`` modules. The IPython module has too much magic in it to be supported. Overall this already provides roughly a 50% speedup when creating new parameterized objects (measured by creating 20k HoloViews Images). In future we could go further and actually rewrite some parts of param as actual Cython, but I suspect that may not be worth it given the decent speedup without it and that most of the remaining time is spent deep copying default parameter values, which can in some cases be avoided by setting ``instantiate`` to ``False`` on a parameter.

Enabled cythonizing of param modules if Cython is available

---

param/parameterized.py

Very minor addition, which gives an easy 5-10% speedup in creating Parameterized objects. Between this, the ``shared_defaults`` context manager, and Cython we can now squeeze out a 3x speedup when creating HoloViews Image Elements.

Skip processing non-parameterized classes in setup_param

---

param/__init__.py
param/parameterized.py
tests/testparameterizedobject.py

This PR adds the ``shared_parameters`` context manager. Here's the docstring, which should explain what it does:
Context manager to share parameter instances when creating
multiple Parameterized objects of the same type. Parameter default
values are instantiated once and cached to be reused when another
Parameterized object of the same type is instantiated.
Can be useful to easily modify large collections of Parameterized
objects at once and can provide a significant speedup.
I've done some basic profiling and this can be a significant boost when instantiating a lot of complex objects.
```python
%%timeit
with param.parameterized.shared_parameters():
hmap = hv.HoloMap({i: hv.Image(np.random.rand(10,10)) for i in range(10000)})
```
```
1 loop, best of 3: 1.77 s per loop
```
vs.
```python …
```

Add shared parameter context manager

---

.travis.yml
doc/index.rst
param/__init__.py

Previously, options in a selection widget created from a Selector parameter would be in an arbitrary order, determined by the underlying Python dictionary type.  With this PR, the original supplied order of options should be preserved.
Under Python 2.6 requires installing the `ordereddict` package, but otherwise should support all the same Python versions as before.

Ordered selection

---

param/__init__.py

I can sort of see why, many years ago, we put the user-supplied softbounds for a numeric parameter into _softbounds and had people call get_soft_bounds instead, but I think now that Python has properties supported in every Python version we support, the design no longer makes much sense.  To make it slightly more reasonble, I've made softbounds be a property, essentially aliasing _softbounds as softbounds, so that no one needs to mess with _softbounds ever.

Allow softbounds to be accessed like an attribute

---

setup.py

Before:
```
ceball@spheroid:~$ docker run --rm continuumio/anaconda:2.3.0 bash -c 'pip install param'
Collecting param
Downloading param-1.4.1.zip (472kB)
Building wheels for collected packages: param
Running setup.py bdist_wheel for param
Complete output from command /opt/conda/bin/python -c "import setuptools;__file__='/tmp/pip-build-6WGJpP/param/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmprwtYGWpip-wheel-:
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/param
copying param/__init__.py -> build/lib.linux-x86_64-2.7/param
copying param/parameterized.py -> build/lib.linux-x86_64-2.7/param
copying param/ipython.py -> …
```

Check there's a working compiler; see #129.

---

.travis.yml

flake8 uses OrderedDict, not present in 2.6, so we should skip it.

Skip flake8 tests on Python 2.6

---

param/__init__.py

param.ObjectSelector and its various subclasses (FileSelector, etc.) keep a list of objects that is used in two very different ways -- either as a fixed, immutable list of all meaningful possibilities (`check_on_set==True`), or as a helpful list of some things that can conveniently be selected in a GUI widget but which could happily include other items too (`check_on_set==False`).
Previously, if a value not in the list of objects was provided and `check_on_set==False`, param would set the value, but it would not change the list of objects.  This was causing problems for paramnb, because ipywidgets/traitlets enforced that the current value of the parameter *must* be on the list of widgets.  This PR ensures that any value explicitly set is put onto the list of allowed objects, so that such …

Add value to the list of objects when ObjectSelector.check_on_set==False

---

param/version.py
tests/testversion.py

Fixes a bug in ``param.Version`` when using pip to install from archive i.e:
```bash
pip install https://github.com/ioam/holoviews/archive/master.zip
```
The SHA was being set correctly via the ``'$Format'`` string but wasn't displaying appropriately (unless the source happened to also be in a dirty git repository).
In addition, users are used to looking at ``holoviews.__version__`` directly instead of ``str(holoviews.__version__)`` which is why I've made the ``repr`` match the string representation.

Version fixes and improvements

---

param/__init__.py

Correctly handle unicode ObjectSelector values in python2. Original code comes from https://github.com/ioam/paramnb/pull/24, but is required here because current unicode handling is broken.

Handled unicode values in ObjectSelector.get_range

---

param/__init__.py

The fact that ObjectSelector doesn't report what the valid values are has annoyed me and would help greatly with usability in holoviews. Is reporting the first 20 items too many?
Here's an example from HoloViews:
>ValueError: left not in Parameter xaxis's list of possible objects, valid options include [top, bottom, bare, top-bare, bottom-bare, None]

ObjectSelector lists possible objects on error

---

.travis.yml
param/__init__.py
tests/testclassselector.py

ClassSelector allows specifying multiple classes as a tuple because isinstance and issubclass support it. However the error handling code does not handle this condition correctly so you get a bad exception message. This PR fixes the exception message and adds unit tests.

Fixed ClassSelector error handling

---

param/parameterized.py

The fact that these two methods don't work caught me out and is currently causing a bug in the released HoloViews 1.7.0. Ideally we'd merge this and release param 1.5.1 immediately.

Added working ParamOverrides get and contains methods

---

setup.py

My opinion about #166. Note that the only people to have been getting cythonized param would be those installing from pip while also having cython and a functioning c compiler.
* Closes #161 (makes it redundant).
* Hopefully allows noarch conda packages, making #167 simpler.
If merged, I would open an issue about considering cythonizing once: 
* there's higher test coverage of param (e.g. resurrecting topographica's tests picked up a problem with cythonized param)
* there are performance tests
Meanwhile, it might be useful to cythonize param as part of testing (e.g. can be useful to catch certain classes of error/bad practice). We could maybe add a command/argument to setup.py to optionally cythonize param.

Remove cython

---

param/version.py
tests/testversion.py

Added ``dev`` argument that allows dev versions to be handled like regular release versions. I'm happy to add more unit tests to make sure everyone is satisfied with this addition.

Added argument to param.Version to support dev versions

---

.travis.yml
conda.recipe/meta.yaml
doc/index.rst

When merged, will make a conda package appear at pyviz/label/dev for any commit to master. The conda package will have the version style shown below:
Note: 
* before merging, should delete the test packages
* needs to be squash merged
* the contained python package `__version__` will be what's hardcoded in the param source code i.e. the most recent release, I think (something that could be addressed in the future)
Another note: I don't have a strong opinion about the version format we use. Also, various similar forms seems to be accepted and 'canonicalized':
```
>>> from packaging.version import Version as V
>>> V('1.2.3.post1.dev0')
<Version('1.2.3.post1.dev0')>
>>> V('1.2.3.post1.dev')
<Version('1.2.3.post1.dev0')>
>>> V('v1.2.3.post1.dev')
<Version('1.2.3.post1.dev0')>
>>> …
```

Upload "latest master" conda package to pyviz/label/dev

---

param/__init__.py

Checking for ``if not obj`` is wrong for objects that define a custom ``__nonzero__`` or ``__len__`` method and this appears to be the cause of multiple bugs in HoloViews. It's particularly bad because this happens during Parameterized instantiation, in which case ``__nonzero__`` and ``__len__`` may not yet work because the required attribute may not be set up yet.

Fixed checks for None

---

conda.recipe/meta.yaml
setup.py

Declare that only python 2.7+ is supported (true since #203)
Be explicit about using setuptools (pip always uses setuptools, even if you don't import setuptools).

setup.py cleanup

---

param/version.py

From #224. I've pasted in the old Version class; it gets used if Version() is called in the old way.
Is this kind of thing just a terrible idea/weekend joke, or could it fly? I guess others would rather just forget about the old class and move on...?

Provide old Version class if called in old way

---

.travis.yml
tox.ini

Python 3.7 is scheduled for release in June.
This PR doesn't have to be merged - we could just update this PR from time to time.

Add python 3.7 to linux test matrix

---

param/parameterized.py
tests/API1/testparameterizedobject.py

* Restores `_set_name()` to Parameterized (still deprecated).
* Restores `state_push()` and `state_pop()` to Parameterized - and don't deprecate - because subclasses may be overriding. 
If we want to change/remove `Parameters._set_name()` and/or `Parameterized.state_push/pop()`, that should be discussed separately (e.g. #233).

param namespace fixups

---

param/__init__.py
param/parameterized.py
tests/API0/teststringparam.py
tests/API1/teststringparam.py

Hello,
As mentioned in issue #240, i have added regular expression matching to the String Parameter sub-class.
I also added relative API0 and API1 tests, but was only able to run the API0 tests.
(In addition i corrected typos in the Number Parameter sub-class)
param is a great package so I was happy to add this small contribution
Best, 
Thomas Deneux

Added regular expression to 'String' Parameter

---

param/parameterized.py
tests/API0/teststringparam.py
tests/API1/teststringparam.py

* Renamed regexp to regex (matching python docs, and regexp in method names is deprecated in unittest2/python3). 
* Altered regex example to encourage creation of meaningful Parameter subclasses.
* Added string and regex values to the failure-to-match error message.

'regex string' fixups

---

param/__init__.py
param/parameterized.py

* Support python 2.7 and python3 <3.6
* Keep list of watched methods on class (avoids having to search all attributes at instantiation time)

Dependencies: support more pythons and begin storing dependency info in more convenient way

---

param/__init__.py
param/parameterized.py

For now, see http://nbviewer.jupyter.org/github/ceball/snippets/blob/master/param_dependencies-rendered.ipynb
Or if brave you could try https://mybinder.org/v2/gh/ceball/snippets/master?filepath=param_dependencies.ipynb
(you'll need to re-run the cells yourself when mybinder loads).

Initial go at methods depending on parameters

---

.travis.yml

Mistakenly set to dev tags in recent PR for website building.

Fix release tags in travis file.

---

param/__init__.py
tests/API1/testobjectselector.py

Right now, ObjectSelector accepts a list of objects from which to select, which works well when the objects have a meaningful `name` parameter or `__name__` attribute.  However, one often needs to switch between objects for which you want to use a different representation.  For instance if one defines a selector like this: 
```
video = param.ObjectSelector(objects=["k27MJJLJNT4","aZ1G_Q7ovmc", "BjlQdOK3n5w"])
```
The user will be confronted with a bewildering set of meaningless choices.  Instead, it would be nice to provide a list of readable names associated with each object, as in:
```
video = param.ObjectSelector(objects=dict(AnacondaCon18="k27MJJLJNT4",
SciPy18="aZ1G_Q7ovmc", 
ERDC17="BjlQdOK3n5w"))
```
That way a GUI selection widget can let the users choose between the readable …

Allow ObjectSelector classes to accept a dictionary with names

---

param/parameterized.py

This PR ensures that undecorated methods by default depend on all parameters. This PR will ensure that ``panel`` will listen to all parameter changes by default while holoviews will continue to only listen to changes that have been explicitly declared.

param_depends_on returns all parameters for methods

---

.travis.yml

(Avoids getting pre-release sphinx, which is currently incompatible with nbsite.)

Use released version of nbsite

---

param/parameterized.py
tests/API1/testparamdepends.py

Refactor of param depends and added support for listening to all subobject parameters with ``subobject.param`` spec.

Param depends improvements

---

param/parameterized.py

This is a somewhat subtle bug and I have no minimal example except for trying to run through the panel Param notebook and trying to set ``Example.unbounded_float = 3.14``.

Fixed Parameter __setstate__ bug

---

param/__init__.py
tests/API1/testparamunion.py

This is the results of the discussion from #251. A helper function ``param_union`` was added to ``param/__init__.py`` that allows new parameter objects to be easily initialized from older ones. The behaviour is mostly the same to that discussed, except
- Supports API 1
- Overwrites the value instead of preserving the first
Also added some basic unit tests.

Added param_union, unit tests

---

param/__init__.py
tests/API0/testobjectselector.py
tests/API1/testobjectselector.py

See https://github.com/pyviz/panel/pull/50 for more details.

ObjectSelector support for selecting lists and dicts

---

param/parameterized.py

Simple PR that fixes what I consider incorrect terminology relating to `Change` objects and the other new named tuples.

Renamed attributes of named tuples used by watch

---

param/parameterized.py
tests/API1/testwatch.py

Following the proposal in #269, this PR updates the watch mechanism to ensure changes have actually occurred before triggering the defined watch callbacks.
My next step will be to write another PR that works on the new `trigger` method and batching.

Only trigger watch callbacks on parameter change

---

param/parameterized.py
tests/API1/testwatch.py

Using `watch_values` is useful when you only care about value changes and don't want to handle `Change` objects. In this case, the changed values are passed as `**kwargs`.
Ready for review/merge once the tests are green.

Added watch_values and unwatch_values methods

---

tests/API1/testwatch.py
tests/API1/utils.py

This PR moves ``MockLoggingHandler`` from HoloViews to param where it is more appropriate. One example unit test is also added here to show how it is used. Once a new version of param is release, I'll be able to remove the equivalent code from HoloViews.

Added utility to test logging output

---

param/parameterized.py
tests/API1/testwatch.py

Addresses #273. Note this is a simple search and replace: I am assuming there are no backwards compatibility implications (e.g renaming a slot) because this whole mechanism is new enough that it hasn't been released yet.

Renamed 'subscribers' to 'watchers' throughout

---

param/parameterized.py

The code was letting array comparisons slip past which meant they would fail when the boolean arrays were being coerced to bools. This PR ensures the coercion happens inside the try/except, which means that it fails gracefully.

Ensured that param changed comparisons fail on array

---

param/parameterized.py
tests/API1/testwatch.py

We decided we wanted this boolean option independently of whether we implement the `trigger` method or not.

Added onlychanged flag for watch method

---

param/parameterized.py
tests/API1/testwatch.py

Implements what I suggested in https://github.com/ioam/param/issues/269 and supersedes https://github.com/ioam/param/pull/277 if we decide to go with this approach. I haven't yet defined any comparisons for types beyond Python literals. Here's what a comparison function definition for a NumPy array would look like (without explicitly importing numpy and registering the equality by type):
```python
def is_numpy(obj):
if 'numpy' not in sys.modules: return False
import numpy as np
return isinstance(obj, np.ndarray)
def array_equal(obj1, obj2):
import numpy as np
return np.array_equal(obj1, obj2)
Comparator.equalities[is_numpy] = array_equal
Comparator.equalities[np.ndarray] = np.array_equal
```

Add Comparator to detect changes in arbitrary objects

---

param/parameterized.py
tests/API1/testwatch.py

Simple bug fix to guard against errors when the type of a parameter changes.

Fixed bugs in Comparator when type changes

---

param/parameterized.py

This makes the Watcher more self-contained, providing all the information needed to subsequently unwatch it.

Add Watcher attributes for the instance and class being watched on

---

param/parameterized.py
tests/API1/testwatch.py

The batching queues and the flag were all being set on a class' Parameters (i.e. ``.param``) object, which caused very strange behavior when there were multiple batched calls triggering each other. Additionally unconditionally returning the BATCHED flag to False once done with batching was disabling batching entirely for nested batch calls.

Ensure batching happens on instances Parameters object

---

param/parameterized.py
tests/API1/testwatch.py

In the previous PR which fixed batching I assumed that the ``obj`` would always be provided but if you look at ``Parameterized.__set__`` it is not provided if ``self._owner`` is the object.

Fixed bug when watching class parameter

---

param/parameterized.py

This generalizes things as `Change` tuples didn't always represent changes (e.g when `old==new`).

Renamed Change named tuples to Event

---

param/parameterized.py
tests/API1/testwatch.py

This PR lets `Event` objects declare their type: either 'set', 'changed' or 'triggered'. If 'set', then the event was due to anything where `onlychanged=False`, if 'changed' then `onlychanged=True` and 'triggered' means the `trigger` methods was used.

Introduced types field for watch Event objects

---

param/parameterized.py
tests/API1/testwatch.py

This bug took me a long time to track down. Currently when a watch callback is triggered in batched mode any changes that callback makes to another parameter will not trigger watchers on those parameters. This is because these events will simply continue to be queued and that queue won't be processed until the next time a batched callback comes along. Therefore batching mode should be disabled before any other updates are processed.
The alternative here would be for ``batch_callbacks`` to process the queue in a while loop until it is empty, i.e. after each watcher is called any new events added would be added to the queue to process. That provides no actual benefits over this simpler approach though.
Been wondering for a week why the play button icon wasn't updating when I toggled it.

Fixed bug when batched watch callback sets other parameters

---

numbergen/__init__.py
param/parameterized.py
param/version.py
tests/API0/testclassselector.py
tests/API0/testdefaults.py
tests/API0/testipythonmagic.py
tests/API1/testclassselector.py
tests/API1/testdefaults.py
tests/API1/testipythonmagic.py
tests/API1/testwatch.py
tests/__init__.py
tox.ini

The latest flake8 release seems to stricter about line breaks and escape sequences.

Fixed various flake issues

---

param/parameterized.py
tests/API1/testparamoutput.py

This PR adds support for declaring multiple outputs as the return type of a method. The expectation is that if there are multiple outputs they are expected to be in a tuple. To declare multiple outputs two main formats are supported, either as keywords (only in py>=3.6) or for compatibility with older python versions it also supports tuples:
@output(number=param.Number(), string=param.String())
def some_method(self):
...
@output(('number', param.Number()), ('string', param.String()))
def some_method(self):
...
The ``parameterized.param.outputs()`` method returns a dictionary like this:
```python
{'number': (param.Number(), parameterized.some_method, 0),
'string': (param.String(), parameterized.some_method, 1)} 
```
i.e. a mapping from the output's name to a tuple of the (param_type, …

Added support for multiple outputs

---

param/__init__.py
tests/API1/testselector.py

This is nice and convenient in most cases with a shorter name. Addresses the second item listed in https://github.com/pyviz/datashader/issues/698.

Updated Selector to be a user friendly ObjectSelector

---

param/__init__.py

This PR adds a utility that has cropped up several times and has resulted in some level of code duplication. This has cropped up on some dashboarding projects and is used in the HoloViews [`Streams.define`](https://github.com/pyviz/holoviews/blob/master/holoviews/streams.py#L85) classmethod. It is also relevant to the sort of promotion used to generate widgets in the style of `interact` (e.g panel's `interact` function).
Currently WIP as there are several things to discuss:
* Tuples: These map to `param.Tuple` but if the elements are numeric types this could be mapped to `param.NumericTuple`. Note that numeric 2-tuples can also define the bounds on numeric types but you would need a default value: i.e I don't think you can map numeric 2-tuples to a number parameter including bounds. There …

Added keywords_to_params promotion utility

---

param/__init__.py
param/ipython.py
param/parameterized.py
tests/API1/testparameterizedobject.py
tests/API1/testwatch.py

This PR implements the notion of an instance parameter which can be accessed using a new API. All parameters can in theory become instance parameters (as long as the new ``per_instance`` slot is set to True). The main balance to strike here is that a) we do not want to pay the cost of copying parameters for all instances and b) we do not want users to have to add any special boilerplate to get instance parameters.
The approach I've therefore taken is to only make a copy of a parameter when it is actually needed. This means that all existing param code will never pay the cost of making instance parameters, there's only two situations where the per instance copy is made:
1. When a instance parameter attribute is watched. This is because you do not want events triggered by changes on the …

Add support for instance parameters

---

param/__init__.py
param/parameterized.py
tests/API1/testwatch.py

Fixes https://github.com/pyviz/param/issues/322

Ensure all watchers are executed in scheduling order

---

param/parameterized.py
tests/API1/testwatch.py

Currently batch watching merges all events into a single dictionary by name and matches the watcher to dispatch it to by name. This ignores the fact that there may be multiple events for different attributes of the parameter (e.g. ``value``, ``object``, ``precedence`` etc.) and that each attribute might have different watchers. 
Previously this was not problematic but in recent PRs batching is now used to ensure that events are queued correctly internally which means parameter attribute change events can end up in the batch queue.
This PR ensures that the batch watching code correctly respect the ``what`` argument, which describes which parameter attribute is triggering the event.

Support batch watch on Parameter attributes

---

param/__init__.py
tests/API1/testnumberparameter.py

This adds a step slot to `Number` parameters. This will be useful for any library that maps parameters to widgets (e.g panel).
TODO:

Added a step slot to param.Parameter

---

param/parameterized.py
tests/API1/testwatch.py

Ensure that param watch decorator is resolved using MRO

---

param/__init__.py
param/parameterized.py
tests/API1/testparamdepends.py

This PR extends the `depends` decorator to allow it to decorate regular functions not just methods on Parameterized classes. Unlike the usage with a method the decorator must be given parameter instances associated with a Parameterized object. This makes it very easy to tie a simple function to the state of a Parameterized class, scheduling callbacks, and if used in conjunction with Panel makes a reactive pattern possible without requiring users to write entire classes.
The usage with Panel is the primary motivator here, so let us see some examples. Here is a simple example tying the value of a ``FloatSlider`` to the function: 
Another simple example is this implementation of a plot selector using hvplot:
The decorator allows defining both regular arguments and keyword arguments to be …

Allow param.depends to annotate functions

---

param/parameterized.py

Fixes a small bug in the validation logic for param.depends.

Ensure that param.depends allows mixed Parameter types

---

param/parameterized.py
tests/API1/testwatch.py

The events now get emitted but still have the wrong type. The complexity of fixing that is too large now so I've opened #344 for now.
Fixes https://github.com/pyviz/panel/issues/450

 Ensure trigger method doesn't drop events in batched mode

---

param/__init__.py
tests/API0/testcalendardateparam.py
tests/API0/testcalendardaterangeparam.py
tests/API1/testcalendardateparam.py
tests/API1/testcalendardaterangeparam.py
tests/API1/testnumberparameter.py

Rename `Date` into `DateTime` and add `CalendarDate` (for `date`).
Same for `DateRange`.
For compatiblity `Date` is an alias for `DateTime`. The idea is to rename `CalendarDate` into `Date` later on.
see #346 and #168

Date and datetime

---

param/__init__.py

In Python 3.3, abstract collections were moved from the ``collections`` module to the submodule ``collections.abc``. In 3.7, importing abstract collections directly from ``collections`` results in a ``DeprecationWarning``. In python 3.8, ``collections`` will no longer contain abstract base classes.
This PR tries to import and use ``collections.abc``. If it fails (python 2.7), it falls back to ``collections``
I was tired of DeprecationWarnings :D

Import abstract collections from collections.abc where possible

---

param/parameterized.py
tests/API1/testwatch.py

In order to fix https://github.com/pyviz/param/issues/322 I implemented a scheme by which watch calls would execute in the order the user scheduled them. This meant that if a watch callback triggered another event, that event would not get called until all previous events had been processed. 
This fix was important for certain (relatively rare) scenarios and ensured correctness, however it also has the quite annoying side-effect that you cannot define a watch callback which temporarily sets and unsets a parameter that has some side-effect, e.g. when you click a button in panel you might want to disable that button while you perform some computation (e.g. see #350), in this scenario you want param to eagerly execute any callbacks as they are triggered. The distinction here is akin to …

Add eager option to watch calls

---

param/__init__.py
tests/API1/testclassselector.py

ClassSelector allowed using `class_=some_tuple` but ClassSelector.get_range() would error in that case.

Fix ClassSelector.get_range() for class_ tuple

---

.travis.yml
README.rst
doc/conf.py
examples/About.ipynb
param/version.py

This substitutes pyviz for holoviz where appropriate (in some places the code would need to be changed but that is for a different PR)

Update links and text to point to holoviz.org

---

param/parameterized.py

The `__new__` constructor method is overridden in the `ParameterizedFunction`  class to make it possible to call a parameterized function as if it were a regular function.  The `__new__` constructor calls `ParameterizedFunction.instance()` to create an instance of the class, and then calls the instance's `__call__` method to execute the function.
Previously, the `instance()` method was called without any keyword arguments and then the user provided arguments were passed to the `__call__` method on the instance.
This PR simply passes any user provided keyword arguments to `instance` as well as `__call__`, this way the user provided arguments are saved in the parameterized function instance.
I ran into this issue while working on `linked_selections` in HoloViews.  Without this change, the …

include params when calling instance in __new__

---

param/parameterized.py
tests/API1/testparameterizedobject.py

Spotted while working on https://github.com/holoviz/holoviews/pull/4201.

Internal removal of old API usage

---

LICENSE.txt

Just happened to notice the license is out of date. Do we really have to keep updating it? (I mean the copyright years - not just because we keep changing the team name 😂.)
(I also tried to make the third paragraph independent of the team name based on the text at https://opensource.org/licenses/BSD-3-Clause. But could we drop the third paragraph entirely and move to https://opensource.org/licenses/BSD-2-Clause?)
Also: HoloViz team? HoloViz? HoloViz developers (https://github.com/orgs/holoviz/teams/holoviz-dev)? Param developers? Param contributors? Etc

Update years and team name.

---

param/parameterized.py

Reverts #367 because it has a number of undesirable side-effects. There are plenty of ParameterizedFunctions which accept kwargs which are not parameters and this generates warnings for all of them. We'll apply a more limited fix to address the original need in the original PR.

Revert Include params when calling instance in __new__ (#367)

---

param/parameterized.py

Supersedes https://github.com/holoviz/param/pull/384
The reasoning behind this is that having accessors which hold a reference back to the Parameterized object create a circular reference which stops CPython's garbage collection from immediately collecting a Parameterized instance when it is no longer referenced by any external object instead having to wait for the next `gc.collect()` cycle.

Turn .param into a property

---

.travis.yml
doc/conf.py

@philippjfr @jlstevens I updated the conf.py file to use sphinx_holoviz_theme

update the html theme to use sphinx_holoviz_theme

---

param/version.py

In some weird environments, param's way of retrieving version information has many bugs (since it opens a subprocess to call git, for instance, which gives problems when Python processes are created with systems such as Supervisor or Gunicorn). This commit adds the option for the library to keep on going, even if the version cannot be correctly retreived.
It turns out that param.version is running (or at least trying to run) some git commands in order to retrieve the version. The way the git commands are launched is through subprocess.Popen() as you can see here: https://github.com/holoviz/param/blob/7d2d2a848dc79d9741709702f8b47f87497701b0/param/version.py#L23
And well, it turns out that subprocess.Popen() is nor particularly async-friendly when spawned from an os fork instruction (just …

Prevent param.version from failing when used alongside async frameworks

---

param/parameterized.py

Allows using `__iadd__` on parameters that support in-place operations even if it is constant as long as the return value `is` the same as the previous parameter value. Note that this is only my particular usecase and this will also allow any other `__i<operator>__` method and even `parameterized.object = parameterized.object` but I don't think any of those are harmful since it does not break the `constant` contract of changing the actual object identity.
```python
import param
class Test(param.Parameterized):
list = param.List([], constant=True)
test = Test()
test.list += [1, 2, 3]
```

Allow using iadd on constant parameter

---

param/ipython.py

I tried the ipython magics %params and saw that broken link: http://ioam.github.io/param/

Fix broken link in ipython %params message

---

param/parameterized.py
tests/API1/testwatch.py

When a Parameterized is (deep)copied the watchers on it are copied along with the rest of the internal state. The problem with this is that these watchers will still call methods on the original, not on the copy. Therefore we have to override `__setstate__` behavior to detect internal watchers (i.e. methods on the instance and those set up by decorating methods using `@param.depends(..., watch=True)`) and correctly copy them.
Fixes https://github.com/holoviz/param/issues/407
Ping @sdc50

Ensure that Parameterized remaps watchers on copy

---

param/__init__.py
param/parameterized.py
param/serializer.py
setup.py
tests/API1/testjsonserialization.py

This PR outlines another attempt at serializing/deserializing to JSON (for reference see
#153 for earlier attempts at tackling this problem). The design used in this PR aims to try to keep things simpler but also adds the ability to generate [JSON Schemas](https://json-schema.org/) which should help with testing as well as specification of allowable parameter values (e.g this could be used to specify suitable widgets in panel).
This PR is based off the ideas suggested in #382.

JSON serialization and schema generation

---

param/parameterized.py

A horrible bug where instance parameters could potentially share watchers of class parameters causing really strange interactions.

Make copy of watchers dictionary on instance parameters

---

param/parameterized.py
param/serializer.py
tests/API1/testjsonserialization.py

Refactors the JSONSerializer into something that makes a bit more sense to me. There are now methods to serialize/deserialize a set of parameters into a single serialized object, and another set of methods to serialize/deserialize individual parameter values.

Refactor JSONSerializer

---

param/parameterized.py

Only use `_instance_params` when the class has been initialized.

Ensure Parameterized.param.objects works with uninitialized object

---

param/parameterized.py

Relatively silly micro-optimizations which do add up when you're creating thousands of objects. In my particular usecase 5000 parameterized objects were created and these changes shaved 50-100 ms off from the 500 ms spent on creating parameterized objects.

Micro optimizations

---

setup.py

This pull request adds description links to the setup.py using the `project_urls` key. 
* [An example setup for mflow](https://github.com/mlflow/mlflow/pull/2431/files)
* This PR adds more entries the project link on pypi see [mlflow](https://pypi.org/project/mlflow/)
In the descriptive links I've placed canonical things like Documentation, Releases, and Bug Tracker. I propose adding panel docs as complements to the param docs.
closes #418

Add project links to setup to add links to pypi

---

.travis.yml

This adds support for building dev and release websites with commit messages containing `website_dev` and `website_release` respectively, and building building from tags using `website_release` and `website_dev`, as well as tags of the format `v1.3.1a4` for dev, and `v1.3.1A4` for release.

add commit message build support

---

param/__init__.py

closes #303 by removing the allow_none parameter from the function signature.

Ensure the color class applies allow_none

---

.travis.yml
numbergen/__init__.py
param/__init__.py
param/parameterized.py
setup.cfg
setup.py
tests/API0/testtimedependent.py
tests/API1/testjsonserialization.py
tests/API1/testtimedependent.py
tests/__init__.py
tox.ini

* Remove redundant handling for python<2.7 in test suite (we don't support python<2.7).
* Don't use python 2.7 as a primary test environment on travis, use python 3.7. (python 2.7 is still tested.)
* Follow existing pattern for testing with optional components: jsonschema
* Re-enable testing with gmpy present
* Add python 3.9 on travis (3.9 comes out soon).
* All tests are now being run on travis.
* Measure coverage with all optional tests running.
* Add numbergen to modules being checked for coverage.
* Merged duplicate/inconsistent flake8 sections, with a set of rules that lead to no complaints about trivial stuff.
* Replaced a named lambda with a function (because flake8 complained :) I don't have much opinion).
* Fix various indentation issues and add indentation to flake checks (we …

Test suite fixups

---

param/parameterized.py

Supposed to fix #415...but let's see if the existing test suite passes first...
I probably need a review from @philippjfr at this point before I go further, as 1. I'm a bit out of practice ;) and 2. seemingly if I ever try to inspect anything param-ish using pdb, I get `Fatal Python error: Cannot recover from stack overflow` and a core dump :( (no doubt related to the ever recurring repr problems).
To do:

Group depends for watched deps within a class

---

param/parameterized.py
tests/API0/testparameterizedobject.py
tests/API1/testparameterizedobject.py
tests/README.md

Fix the (longstanding) assumption in param's abstract class mechanism that abstract classes don't start with a leading underscore.
> Any identifier of the form __spam (at least two leading underscores, at most one trailing underscore) is textually replaced with _classname__spam, where classname is the current class name with leading underscore(s) stripped. This mangling is done without regard to the syntactic position of the identifier, as long as it occurs within the definition of a class.
(https://docs.python.org/2/tutorial/classes.html)
https://github.com/holoviz/param/blob/301b9617e84f3578364393d5ae30c452d1c19cd0/param/parameterized.py#L2074-L2094
(i.e. param does not do the same thing as python)
(originally from https://github.com/holoviz/param/pull/423#issuecomment-694526493)
Also …

Fix .abstract for classes named with leading underscore(s)

---

param/__init__.py

Serialization must be symmetric otherwise things break (e.g. URL syncing which makes use of param serialization is broken without this).

Fix serialization of Tuple

---

param/__init__.py
param/serializer.py

Here is one way to address https://github.com/holoviz/param/issues/455, namely to make sure the `List` parameter does not use the same `class_` slot as `ClassSelector` (I called it `list_class` for now instead).
Generally, I'm not sure why parameters inherit previous slot values at all (when they have a value of None) tbh...

Avoid clashing class_ slot in List parameter

---

.github/workflows/test.yml
param/version.py

This brings the fixed git remote check implemented in https://github.com/pyviz-dev/autover/pull/67 to `param.Version` to 
address #468. The longer terms fix is in https://github.com/pyviz-dev/autover/pull/66 which will be merged once the test failures are resolved.

Ports over fix from autover/pull/67 to param

---

param/parameterized.py

Most of the Parameter attributes accepted were undocumented, but they are now documented in the constructor. Fixes https://github.com/holoviz/param/issues/74 . Supersedes #478.

Expanded Param docstring

---

param/__init__.py
param/parameterized.py
tests/API0/testclassselector.py
tests/API1/testclassselector.py
tests/API1/testpandas.py

Adds an `_on_set` method to all Parameters, this allows Parameters to trigger actions when one of its attributes changes. This is used to update the list of valid paths when `(Multi)FileSelector.path` is set.
Fixes https://github.com/holoviz/param/issues/412

Update FileSelector parameters when setting path

---

param/__init__.py
tests/API1/testlist.py

Fixed validation for List parameters, which was broken in https://github.com/holoviz/param/commit/bf3d324ddaa597a64585177662e0d9e6287a2ece because the new `_validate_bounds()` and `_validate_item_type()` methods weren't called by the default implementation of `_validate()`. Closes #491.

Fixed List validation

---

param/__init__.py

Path is documented as accepting both files and folders (directories), but it was only accepting files.  Fixed to make Path check only that the path exists, not whether it is a file or folder. Also simplified the logic overall. Marked API since the behavior has apparently never matched the documented API; now it should match the previously documented API.

Fixed Path to allow folders, as already documented

---

param/parameterized.py

Addresses #209 and #396 to avoid infinite recursion when printing a Parameterized object that contains an indirect reference to itself. 
First tried using `reprlib.recursive_repr`, which seemed to work for repr itself, but did not address `pprint`, because it did not allow the decorated method to have any extra arguments. Luckily the implementation is straightforward, so I copied it from https://github.com/python/cpython/blob/3.2/Lib/reprlib.py and changed it to handle args and kwargs.  I did have to change `from _thread import get_ident` to avoid private API, but it seems the same as `from threading import get_ident`, which appears to work the same.
I haven't run the test suite yet, but it addresses #209:
```python
import param
b = param.Parameter()
class …
```

Avoid recursive repr issues

---

param/__init__.py
tests/API1/testobjectselector.py

Replace ObjectSelector with Selector

---

.github/workflows/docs.yml
doc/index.md
doc/reference.rst

Speculative attempt to use Panel's doc build configuration to see if it will get the reference manual building on a separate page per module, as Panel's does.

Copy docs workflow from panel

---

doc/reference.rst
doc/roadmap.md

Doc tweaks

---

.github/workflows/test.yml
.gitignore
setup.cfg
setup.py
tests/API0/testcompositeparams.py
tests/API0/testdefaults.py
tests/API0/testdynamicparams.py
tests/API0/testlistselector.py
tests/API0/testnumbergen.py
tests/API0/testnumpy.py
tests/API0/testobjectselector.py
tests/API0/testparameterizedobject.py
tests/API0/testparameterizedrepr.py
tests/API0/testtimedependent.py
tests/API1/testcompositeparams.py
tests/API1/testdefaults.py
tests/API1/testdynamicparams.py
tests/API1/testjsonserialization.py
tests/API1/testlist.py
tests/API1/testlistselector.py
tests/API1/testnumbergen.py
tests/API1/testnumpy.py
tests/API1/testobjectselector.py
tests/API1/testpandas.py
tests/API1/testparameterizedobject.py
tests/API1/testparameterizedrepr.py
tests/API1/testselector.py
tests/API1/testtimedependent.py
tests/API1/testwatch.py
tox.ini

In line with what was done partially in #423, the goal of this PR is to replace nose by pytest:
When this is done, some optional tasks could be tackled such as fixing the warnings already spotted in #423, switching to fixtures when relevant...

Replace nose with pytest

---

param/parameterized.py
tests/API0/testclassselector.py
tests/API0/testdefaults.py
tests/API0/teststringparam.py
tests/API1/__init__.py
tests/API1/testclassselector.py
tests/API1/testdefaults.py
tests/API1/testjsonserialization.py
tests/API1/testnumberparameter.py
tests/API1/testpandas.py
tests/API1/teststringparam.py

- Fixes warnings from deprecated assertRaisesRegexp and assertEquals method calls, which have been renamed assertRaisesRegex and assertEqual in more recent Python versions. Adds an alias to those methods if used with python27.
- Skip ClassSelector defaults test that was failing on my laptop even though it passed on CI. Wasn't really testing much anyway, since ClassSelector cannot be instantiated with an empty argument list.
- Switched from `inspect.getargspec` to the py3 version `inspect.getfullargspec`, which is similar but splits `keyword` args into `varkw` (**) and kw-only args.  Falls back to getargspec on Python2. Might need more attention, but seems to work.

Address warnings from test suite

---

param/__init__.py
param/parameterized.py

Adds the `script_repr` function to the main param module namespace for ease of use, and provides default values for all parameters. All `script_repr` options now match the `pprint()` function, but have different defaults suitable for generating a script rather than a prettyprinted terminal representation. Also adds a `show_imports` argument (defaulting to true) which adds the collected import statements to the top of the script.
The only non-backwards-compatible change should be that the pprint function no longer checks that a Parameterized object has a script_repr method if it doesn't have a pprint method. Both methods have been implemented in Param for many years now, and so it seems unlikely that a script_repr would exist with no pprint. If it does (e.g. in topographica?), it will need …

Cleaned up script_repr

---

.gitignore
doc/user_guide/index.md
examples/user_guide/Dynamic_Parameters.ipynb
numbergen/__init__.py

Added user guide for Dynamic parameters and the numbergen module.
Also added prettyprinting for the underlying binary and unary numbergen operators so that the displayed representations would be readable; should also improve the script_repr representation of numbergen expressions.

Dynamic Parameters user guide

---

tests/API1/testnumberparameter.py

It was wrongly a class rather than an instance.

Fix test_initialization_without_step_instance

---

param/version.py

Previous regexp would have matched "vim" and "vis" and "van" as valid version strings, which surely they are not. Presumably also needs fixing on autover.

Fixed version regexp

---

doc/user_guide/index.md
examples/user_guide/Dependencies_and_Watchers.ipynb
examples/user_guide/Parameters.ipynb
param/parameterized.py
setup.py

Merging this will make the Param User Guide complete for the first time in history!  Still needs some polish and possible reorganization, but the docs at least now cover (or are intended to cover) all of the public API and functionality of param.
This PR includes some minor changes to Param itself that should not affect backwards compatibility:
1. The context manager `param.parameterized.batch_watch` accepted two optional arguments (`enable` and `run`) that shouldn't be part of the public API as they are difficult to explain and shouldn't be needed by end users. Because the name was confusing (it doesn't watch things in batch, it batches up events created when calling watchers), created a new public API version called `param.parameterized.batch_call_watchers`, accepting only the single …

Added Dependencies_and_Watchers user guide

---

conda.recipe/meta.yaml
setup.cfg
tests/API1/testtimedependent.py

`nose` was still expected by `conda build` to run the test suite, which couldn't work at all since it was replaced recently by pytest.
Part of this PR I've also decided to move the last doctest (param.Time) to a unit test. Why? Because conda build failed by simply replacing `nosetests tests` by `pytest tests`. It executes this from a folder that only includes the subfolder `tests`, and the command that was set to tell pytest to look for doctest to execute required the subfolders param and numberben to be also there (pytest tests param numbergen --doc-modules).
There may have been a way to configure pytest to cover this case but I thought it was just simpler to remove that last doctest. This makes even more sense now since param has some nice docs :)
Note that I've not removed the docstest …

Fix conda build

---

examples/user_guide/Parameters.ipynb

Fixes https://github.com/holoviz/param/issues/567 .

Fixed description of shared_parameters

---

param/parameterized.py

Certain functions may raise an error when passed to `inspect.iscoroutinefunction`.

Make iscoroutinefunction more robust

---

param/parameterized.py
tests/API1/testparamdepends.py

Fix misspelled parameter

---

param/__init__.py
param/serializer.py
tests/API1/testjsonserialization.py

Simple fix that addresses https://github.com/holoviz/param/issues/578 issue for `None` valued `Date` parameters and does the same for `CalendarDate` parameters.

Updated JSON serialization of Date and CalendarDate to support None

---

.github/workflows/test.yml

Specify that the CI should run `pypy-3.7` instead of just `pypy3` since the latter defaulted to pypy-3.6 that is not available on MacOS 11.

CI: run pypy 3.7 instead of 3.6

---

param/parameterized.py

Ensures that `param.depends` wraps async coroutines appropriately.

Support async coroutines in param.depends

---

.github/workflows/test.yml
tox.ini

The CI is already running on Python 3.10 but was avoiding running a few tests because at the time it was set a few packages were not yet available on Python 3.10

CI: Run more tests on Python 3.10

---

param/parameterized.py

Required for https://github.com/holoviz/panel/issues/3262 to work

Handle async functions in depends with watch=True

---

param/parameterized.py

Since a `Watcher` is simply a tuple a check like `watcher not in self_._watchers` effectively results in an equality comparison on all the objects inside the watcher tuple, including the Parameterized instance the watcher is attached to. Not all Parameterized objects implement equality checks that make sense in this context so to avoid this we only check for identity.

Avoid equality check on Watcher

---

param/parameterized.py
tests/API1/testwatch.py

Look at whole spec name when determing dynamic watchers

---

doc/index.md

Since there's already the GitHub icon link in the navbar.

Remove the github source link from the navbar

---

.github/workflows/build.yaml
.github/workflows/docs.yaml
.github/workflows/downstream_tests.yaml
.github/workflows/test.yaml

* The test, build and doc workflows are set to run every Sunday on a dry-run mode
* Add a downstream test workflow that will trigger the tests of packages depending on Param on every Param release

Schedule CI workflows and add downstream tests

---

param/__init__.py
tests/API1/testjsonserialization.py

I got the following error while working on a Lumen app that has a DateRange filter widget synced to the URL:
```
File "/Users/mliquet/miniconda3/envs/lumen-dev37/lib/python3.7/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```
We found out that the `DateRange` and `CalendarRange` parameters inherit from the `Tuple` parameter (de)serialization methods, while they should override these methods as Python's `json` module can't serialize datetime objects (`import datetime as dt, json; json.dumps(dt.datetime.now())` raises the TypeError mentioned above).
This PR adds these methods to the two parameters, and test them. I've added tests, including tests that use `np.datetime64` and …

Allow (de)serializing CalendarRange and DateRange Parameters

---

param/__init__.py
tests/API1/testdaterangeparam.py

Noticed that the `DateRange` parameter was not checking that the value provided is a `tuple`, which it should be given that `DateRange` inherits from Tuple.
I've also changed the error message reported when one of the values is not of the correct type:
DateRange parameter 'a' only takes date/datetime values, not type float.
This is slightly different formatting compared to the messages reported by other Parameters, e.g. with a List:
List parameter None must be a list, not an object of type <class 'str'>.
Notice `of type float` vs. `of type <class 'str'>`. If the latter is preferred, I could update the error messages of the other Parameters.

Improve DateRange validation

---

param/__init__.py

Not all objects are hashable so the `named_objs` implementation has started causing some errors (e.g. because mpl colormaps aren't hashable anymore). For unhashable objects we try to reverse map the objects by identity.

Ensure named_objs does not fail on unhashable objects

---

param/__init__.py
param/parameterized.py
tests/API1/testcomparator.py

Discovered this bug while working on https://github.com/holoviz/lumen/pull/276
The `Comparator` class didn't support `datetime.date`, `datetime.datetime` and `np.datetime64` object. This meant that, if a parameter value was set to its old value, Param would still see it as a new value and would let potential watchers be executed, while they should not. This caused problems for Panel bidirectional links which don't check for equality but rely on Param.
I see that other types aren't supported, like Numpy Arrays, Pandas DataFrame, or frozensets. If more types should be added, let's come up with a list and add them in another PR.

Support comparing date-like objects

---

param/__init__.py
tests/API1/testutils.py

Implementing the suggestion in https://github.com/holoviz/param/pull/629#discussion_r876410658, **needs https://github.com/holoviz/param/pull/629 to be merged first**
`guess_param_types` is actually not used at all across HoloViz and not documented. The PR that added this utility - https://github.com/holoviz/param/pull/317 - says that it "has cropped up several times and has resulted in some level of code duplication" and points to HoloViews [Streams.define](https://github.com/pyviz/holoviews/blob/master/holoviews/streams.py#L85) classmethod which indeed could make use of this utility, since it's basically inlining a partial implementation of it.
https://github.com/holoviz/param/pull/317 provides more details about the usefulness of this utility, and on the conversions it doesn't yet …

Don't assume numpy/pandas is available in `guess_param_types` 

---

examples/user_guide/Parameters.ipynb

Addresses #608 by keeping the simple code example but renaming the parameter to `EvenInteger` which expresses the actual check that is performed.

Renamed incorrect BinaryPower example to EvenInteger

---

setup.py

To <0.9 since it has changes to which nbsite/param has not yet been entirely compatible.

Pin the PyData Sphinx Theme

---

numbergen/__init__.py

Fixes #602. See https://github.com/holoviz/param/issues/602#issuecomment-1155147795 for rationale and caveats.
You might instead prefer to use a fixed seed of `13594734499543488215`. That would change the current initial state on older CPython versions (particularly Python 2.7) and on 32-bit builds of CPython; these would become consistent with the initial state on 64-bit builds of supported CPython 3.x versions.

Preserve existing Random seed behavior in Python 3.11

---

.github/workflows/test.yaml

The scheduled runs were failing because the same commit reference was sent to codecov again and again (param master branch isn't updated that often) and apparently codecov has some limits on that. So coverage reports are now uploaded to codecov only on push events, no longer on scheduled events.

CI: update the codecov step

---

param/parameterized.py
tests/API1/testwatch.py

When exposing a parameter with Panel, it might be watched for changes in its `bounds`. Suppose you later want to make a `deepcopy` of this parameter. This will work fine if the parameter is a `Number`, but not if it is e.g. an `Integer`, per this example:
```python
import param
import copy
n = param.Number(default=0)
i = param.Integer(default=0)
obj_1 = A()
obj_1.param.watch(lambda x: x, 'n', 'bounds')
copy.deepcopy(obj_1)  # Works!
obj_2 = A()
obj_2.param.watch(lambda x: x, 'i', 'bounds')
copy.deepcopy(obj_2)  # Raises AttributeError!
```
As I see it, this issue is due to `Parameter.__setattr__` only checking for slot attributes in the class in question itself, and not its superclasses:
https://github.com/holoviz/param/blob/10fff770a50235deab4afad8641a667c754 …

Fix copying when having watchers on e.g. bounds on inherited Parameter types

---

param/__init__.py
tests/API1/testbytesparam.py

Implements https://github.com/holoviz/param/issues/408

Add Bytes parameter

---

param/__init__.py
tests/API1/testdateparam.py

Fixes #578
The changes in #582 made it possible to round-trip serialize <-> deserialize within param. 
A completely valid way to deserialize is to have the serialized values created outside param like this:
``` python
import json
import param
class User(param.Parameterized):
A = param.Date(default=None)
data = json.dumps({"A": None})    # gives: '{"A": null}' <- note that null is not a string
User.param.deserialize_parameters(data)
```
Which raised this error before these changes:
``` python-traceback
Traceback (most recent call last):
File "/home/shh/miniconda3/envs/holoviz/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "/tmp/ipykernel_70470/342607310.py", line 8, in <module> …
```

Allow JSON serialization to work with json.dumps

---

CODE_OF_CONDUCT.md
doc/governance/project-docs/CONTRIBUTING.md
doc/governance/project-docs/GOVERNANCE.md
doc/governance/project-docs/LICENSE.md
doc/governance/project-docs/MEMBERS.md

The files in this pull request should act as examples of how other HoloViz projects could quickly adopt the default project docs using references to the project docs at holoviz/holoviz.
The maintainer list is based on the HoloViz Duties spreadsheet. All three maintainers should participate and/or approve.
I'll mention this at the next docs meeting, but I've written the [guidance to create project docs](https://docs.google.com/document/d/1DSPq7oyR5VyV20g7Ez52tVAkwm12ilfMKZtZumFzAaI/edit?usp=sharing). I'll update this if there are any further changes to this PR.

create initial project governance docs

---

param/__init__.py
tests/API0/testlistselector.py
tests/API1/testlistselector.py

Fixes #527 
I chose to raise a `ValueError` when the type is not a list since raising `ValueError` seems to be what param does in this case. The tests used to catch `TypeError`s in some occasions because param was trying to iterate over non iterables.

ListSelector restricted to list type objects

---

.github/workflows/test.yaml
param/version.py

The test suite did not fetch the tags before the test and would therefore have a version of `"None"`.
With the latest release of `setuptools`, `"None"` was no longer a valid version tag, which was why the tests were failing.

Fetch tags before running tests

---

setup.py
tox.ini
tox27.ini

Found out that because of a bug or user error the XML report produced by `pytest-cov` included the report of only one `__init__.py` file instead of two, coming from Param and Numbergen. It happened to report the one of Numbergen only. This PR runs `coverage` directly which when it builds the XML coverage report does so in a nested way, including the two `__init__.py` files.

Fix the coverage report uploaded to codecov

---

param/parameterized.py
tests/API1/testparameterizedobject.py

Fixes https://github.com/holoviz/param/issues/689

Raise an error when setting `None` to a base Parameter with `allow_None=False`

---

tests/API1/testbooleanparam.py
tests/API1/testbytesparam.py
tests/API1/testcalendardateparam.py
tests/API1/testcalendardaterangeparam.py
tests/API1/testclassselector.py
tests/API1/testcolorparameter.py
tests/API1/testcompositeparams.py
tests/API1/testdateparam.py
tests/API1/testdaterangeparam.py
tests/API1/testdefaults.py
tests/API1/testfileselector.py
tests/API1/testlist.py
tests/API1/testlistselector.py
tests/API1/testmultifileselector.py
tests/API1/testnumberparameter.py
tests/API1/testnumpy.py
tests/API1/testobjectselector.py
tests/API1/testpandas.py
tests/API1/testpathparam.py
tests/API1/testrangeparameter.py
tests/API1/testselector.py
tests/API1/teststringparam.py
tests/API1/testtupleparam.py
tests/API1/testutils.py
tests/API1/utils.py

This PR doesn't touch any file in `param` or `numbergen`, it only adds more tests. Adding tests was motivated by the Sentinel PR, that in its current implementation is dynamically computing the default value of Parameter attributes (e.g. `instantiate`), opposed to know where most of them are just statically declared in the signature definitions. The tests added captures the current default values of most of the Parameters. This PR also adds some rather simple tests to previously untested Parameters such as `Path`.

Add more tests

---

tests/API1/testlist.py
tests/API1/testtupleparam.py

A two tests to capture that the length of a sub-Parameter overriding the default of the parent is correctly computed.

Add a test to Tuple

---

.github/workflows/test.yaml

The CI is pretty slow because:
- the PyPy tests are slow
- it often needs to wait until some MacOS workers are available
This PR reduces the Python version tested to CPython 3.7, 3.9 and 3.11 on the three platforms.
The full matrix is tested on workflow_dispatch, schedule and push+tag events. I bumped the version of PyPy tested from 3.7 to 3.9.

CI: reduce the number of Python versions to test

---

param/__init__.py

Fixes https://github.com/holoviz/param/issues/583
This is effectively a breaking change. The code below used to work fine, while after this change `p.a = None` will raise an error.
```python
import param, numpy as np
class P(param.Parameterized):
a = param.Array(np.zeros((2, 2)))
p = P()
p.a = None
```

Don't hard-code allow_None to True in Array

---

param/__init__.py

Follow up of https://github.com/holoviz/param/pull/744 where `bounds` was removed from `Boolean` but the then useless `bounds` argument in the `Event` constructor - inheriting from `Boolean` - was not removed.

Remove the bounds argument from the Event constructor

---

param/parameterized.py
tests/testparamdepends.py

Fixes #764
This PR fixes a regression that was introduced in https://github.com/holoviz/param/pull/753. It appeared that depending on a method was pretty much untested so I have added some more tests.
When `_spec_to_obj` resolves a dependency on a Parameterized *method*, the type of the resolved method is:
- `FunctionType` if it's a *direct* dependency, as in `@param.depends('method')`. The object holding the reference to the method seen by `_spec_to_obj` is a class.
- `MethodType` if it's a dependency on a sub object, as in `@param.depends('sub.method')`. The object holding the reference to the method seen by `_spec_to_obj` is an instance.
Good to know!
```python
from types import FunctionType, MethodType
class A:
def foo(self): pass
assert isinstance(A.foo, FunctionType)
assert …
```

Fix depending on the method of a sub parameter object

---

param/__init__.py

fixes #756
The decorator adds an extra stack level. 
``` python
import param
class Defaults(param.Parameterized):
filters = param.List(doc="Defaults for Filter objects.", class_=dict)
```
Before: 
After:

Fix stacklevel start

---

param/parameterized.py
tests/testparameterizedobject.py

Fixes https://github.com/holoviz/param/issues/644
Overriding the `name` String Parameter was possible at the class level but it actually had no effect. This PR changes that so it is taken into account. This is the new behavior:
```python
import param
class P(param.Parameterized):
name = param.String(default='other')
assert P.name == 'other'
p = P()
assert p.name == 'other'
```
Overriding is only allowed when `name` is set to be a `String` Parameter, as this is something that `Param` relies on internally for other things. A Parameterized class and its instances will have its `name` overriden if the `default` value of the `name` String Parameter is set to something that is not `None` or not an empty string.
I used this branch to run the test suites of Panel and HoloViews (both somewhat …

Overriding the `name` Parameter is taken into account at the class and instance level

---

param/parameterized.py
tests/testparamdepends.py

Fixes https://github.com/holoviz/param/issues/747
`inst or cls` was used to select `cls` when `inst` was None, except that this fails when `inst` is not None and `inst` is falsey evaluates, as in the example reported in the issue where `__len__` is defined on a Parameterized class and returns `0`. This PR fixes a few occurrences of this bug.

Fix watchers support when the Parameterized instance is falsey

---

param/parameterized.py
tests/testparameterizedobject.py

Another evidence that it's quite easy to break Param despite its own test suite and the test suite of other packages heavily relying on it. This PR fixes a regression introduced in https://github.com/holoviz/param/pull/605, whereby setting constant to `True` was no longer automatically setting `instantiate` to True. I've added tests that would have passed on Param `1.13.0`.

Regression: Re-set instantiate to True when constant is True

---

tests/testaddparameter.py

`add_parameter` has been committed to this repo in 2012, and as far as I can see has been pretty much untested till now but also unchanged so it might just still work as well as it did 11 years ago. Since the private namespace PR is touching it I thought it'd be wise to add at least some basic tests, not to break it entirely.
By the way the only usage I've been able to find is in Lumen:
https://github.com/holoviz/lumen/blob/6bb7bb79f79b0efc1f6fe67af1843df43ba0414f/lumen/variables/base.py#L147

Add tests for `add_parameter`

---

tests/testparameterizedrepr.py

Tests needed to avoid breaking them too easily, as it was done in https://github.com/holoviz/param/pull/767

Add simple tests for pprint and script_repr

---

param/__init__.py
param/_utils.py
param/parameterized.py
tests/testdeprecations.py
tests/testparameterizedobject.py
tests/testparameterizedrepr.py

My priority with this PR was to further clean up the Parameterized namespace, following and even going further the dispositions suggested in https://github.com/holoviz/param/issues/543
- I looked through all the holoviz repos + examples for usage of `.pprint` or `._pprint` and found none, so I decided to remove them all together, using `.param.pprint()` was anyway the recommendation in the Version 1.12.0 release notes.
- The same search showed no usage of `.script_repr` that has been deleted from `Parameterized` and also from `ParameterizedFunction`.
- Instead of just deleting `.state_pop` in favor of `._state_pop`, I decided to move it (and `.state_push`) to `.param._state_pop`. This API isn't documented and was planned to be made private, this is why I chose to make it private on the …

More Param 2.0 API cleanup

---

.github/workflows/test.yaml
pyproject.toml

Bump the minimum required Python version to 3.8 as 3.7 reached EOL, per HEP1.

Drop Python 3.7

---

param/parameterized.py
tests/testparameterizedrepr.py

Fixes https://github.com/holoviz/param/issues/785

Validate that `'self'` is present in the init signature of a Parameterized class

---

examples/user_guide/Parameters.ipynb
param/parameterized.py

Following the discussion in https://github.com/holoviz/param/pull/425.

Make the rich repr only available on the `.param` namespace

---

.gitignore
benchmarks/README.md
benchmarks/asv.conf.json
benchmarks/benchmarks/benchmarks.py

Fixes https://github.com/holoviz/param/issues/165
This PR adds a limited benchmark suite that leverages `asv`. I ran it on my machine with Python 3.11, from commits dating back to v1.11.1 (released in July 2021) to now.
Two PRs have recently degraded the performance (of that limited benchmark):
- https://github.com/holoviz/param/pull/605
- https://github.com/holoviz/param/pull/742
I think before releasing Param 2.0 it would be good to check whether this is acceptable.
---
Of course, more benchmarks could be added in the future.

Add basic benchmark suite

---

param/parameterized.py
tests/testparamdepends.py

Fixes https://github.com/holoviz/param/issues/357
@philippjfr I'm very far from being confident with this change.
This example:
```python
import param
x = param.Number(0)
@param.depends('y', watch=True)
def debug(self): pass
```
Would immediately fail at the class creating time with:
```
Traceback (most recent call last):
File ".mltmess/issue_params.py", line 47, in <module>
File "/Users/mliquet/dev/param/param/parameterized.py", line 2903, in __init__
deps, dynamic_deps = _params_depended_on(minfo, dynamic=False)
File "/Users/mliquet/dev/param/param/parameterized.py", line 640, in _params_depended_on
ddeps, ddynamic_deps = (minfo.cls if minfo.inst is None else minfo.inst).param._spec_to_obj(d, dynamic, intermediate)
File …
```

Resolve non watched references too to catch bad references

---

examples/user_guide/How_Param_Works.ipynb
examples/user_guide/Parameters.ipynb
param/__init__.py
param/parameterized.py
tests/testaddparameter.py
tests/testdynamicparams.py
tests/testparameterizedobject.py

At this stage this is more of a POC, that I wanted to share to see whether it's going in the right direction. The idea with this PR is to cleanup the private namespace of Parameterized classes and instances, mostly by defining a private namespace that we can defend and document, hopefully making it less likely for users to get name collisions. Some additional clean-up/renaming could also be done.
Take this example:
```python
import param
x = param.Number()
a = A(x=2)
```
Ignoring dunder methods and some public & private API meant to be removed for Param 2.0 (https://github.com/holoviz/param/pull/767), these are the attributes (calling `dir()`) of `A` and `a` on the *main* branch currently:
`A`:
```
['_A__params',
'_Parameterized__params',
'_param', …
```

Add a dedicated namespace for private objs on Parameterized

---

param/parameterized.py
tests/testparameterizedobject.py
tests/testselector.py

Fixes https://github.com/holoviz/param/issues/287
Pushing this WIP PR to get some feedback on the approach. The idea is that when:
1. `instantiate` is `True` -> deepcopy `default` and assign it to the local cache (pseudo: `parameterized_obj._X_param_value = deepcopy(parameter.default)`)
2. `constant` is `True` -> don't deepcopy, just assign a reference to `default` to the local cache (pseudo: `parameterized_obj._X_param_value = parameter.default`)
With 1. taking precedence over 2.
The test added in https://github.com/holoviz/param/commit/7635d55e265b432417bad4ed5571fe4c84371037 and that is based on the one given in the issue passes with this change.
Of course this means that if the `default` object is mutable, any change made from a reference will be seen by all the other references, all …

Don't automatically set instantiate to True when constant is True

---

param/__init__.py
tests/testobjectselector.py
tests/testselector.py

Discovered that the sentinel PR introduced a regression, ignoring the value of `allow_None` (which is always a little controversial to use with selectors and you can just add `None` to the objects list) set in the Parameter constructor.

Fix regression that ignored `allow_None` set in a selector

---

param/_utils.py
param/parameterized.py
tests/testdeprecations.py
tests/testnumpy.py
tests/testparameterizedobject.py

Fixes https://github.com/holoviz/param/issues/606
Fixes https://github.com/holoviz/param/issues/179
Supersedes https://github.com/holoviz/param/pull/437
I chose to replace `all_equals` in `.param.values` by `Comparator.is_equal`, which then needed to be extended to deal with objects that have the `_infinitely_iterable` attribute (`Time`). I've had to change the code in `is_equal` a little to fix the support for `predicate: equality`.
As a reminder (https://github.com/holoviz/param/issues/179#issuecomment-362818251), `all_equal` has this weird behavior that `all_equal('aaaa', 'aa')` is True. That behavior is relied upon (intentionally I guess) by `.param.values(onlychanged=True)` so that the Parameterized instance auto-generated name is filtered out of the returned values. I copied code …

Fix `param.pprint` for `Array` parameters by replacing `all_equal` with `Comparator.is_equal` in `values()`

---

param/parameterized.py
pyproject.toml
tests/testparameterizedobject.py
tests/testpickle.py

https://github.com/holoviz/param/pull/766 was merged too quickly, running the HoloViews test suite locally revealed a bunch of new errors:
- setting an attribute in the `__init__` **before** calling `super().__init__` wasn't exerted in Param's test suite but leveraged in HoloViews (https://github.com/holoviz/holoviews/blob/a64cfc544acc94b3806d427912047ca660253587/holoviews/plotting/plot.py#L1168). This is now supported again and tested.
- the private namespace broke pickling when the protocol `0` is used which is apparently used by HoloViews in some cases. This PR fixes the support for that protocol, at least in the sense that the HoloViews unit test suite should now pass. To complete that fix, I have had to remove the compatibility code on `Watcher` that allowed to exclude `precedence` …

Fix issues due to the Parameterized private namespace

---

param/parameterized.py

I was a little surprised to see that Param was always building a docstring for IPython even not in an IPython context. This also came with some side-effects as the pager calls `.param.objects()` which leads to the Parameters being cached on the class:
https://github.com/holoviz/param/blob/b96169f0804fea72488914e1fc38e7c3dd9b9828/param/ipython.py#L63
This can only improve the performance of loading modules with lots of Parameterized classes that have lots of Parameters, no idea by how much though!
However, this of course also affects how the docstring look like in a non IPython context, e.g. in the Python REPL.
Before (colorized output):
```
>>> import param
>>> class P(param.Parameterized):
...   """The class docstring"""
...   x = param.Parameter()
... 
>>> p = P()
>>> print(p.__doc__) …
```

Only build the fancy docstring when in an IPython context

---

examples/user_guide/How_Param_Works.ipynb
param/parameterized.py
tests/testaddparameter.py

The private namespace work made this internal slot useless.

Remove Parameter `_internal_name` slot

---

param/__init__.py
param/_utils.py
tests/testpathparam.py

Fixes https://github.com/holoviz/param/issues/708
It used to only emit a warning which was pretty inconsistent with the other Parameters.
---
I've also introduced a small utility to better format the validation errors raised in `__init__`, planning to open another PR to align all the Parameter errors before the Param 2.0 release.

Raise a `ValueError` when `Path` is set to `None` while not allowed

---

param/parameterized.py
tests/testparameterizedobject.py

Fixes https://github.com/holoviz/param/issues/760
https://github.com/holoviz/param/issues/760 identified that this regression happened in https://github.com/holoviz/param/pull/424. More precisely I've found out it was due to this change https://github.com/holoviz/param/pull/424/files#diff-c8fc4fb68012b66fbf42ad9e0b4714fd96a3a72b83558bc543130d78bd622eb3R1275-R1279 by which Param would  "instantiate" (i.e. materialize a default Parameter value into an instance) the wrong Parameter default. That happened if a Parameter is inherited and isn't re-declared by the subclass, in which case the "instantiated" value would be the one from the first class above in the hierarchy that declares the Parameter.
Instead of the custom class hierarchy traversal I've opted for leveraging …

Materialize default values based on all the parameters available

---

param/__init__.py
param/parameterized.py
tests/testselector.py

Fixes https://github.com/holoviz/param/issues/693
It's been pretty tricky to implement as `Selector` isn't the easiest Parameter to deal with (its setup is quite dynamic) and handling slot values inheritance for it adds an extra level of complexity. The approach I've opted for is to add a method to `Parameter` that subclasses can implement and that is called only after slot values inheritance has completed, to update the Parameter state. In that case, it's used to add the `default` value to `objects` when `check_on_set` is False and `default` is not in there.
I haven't managed to get that to work together with the unbound case so I marked that test as xfailed https://github.com/holoviz/param/compare/fix_checkonset_default?expand=1#diff-df60be25aab735646b74b0a737306d420bec4718b0dadd8323fe8e …

Populate `objects` when `check_on_set` is False and `default` is not in `objects`

---

param/__init__.py
tests/testfileselector.py

Addresses the first issue raised https://github.com/holoviz/param/issues/545, i.e. that the `FileSelector` parameter is not updating its default value to the first path found in `objects`, which is inconsistent with how `Selector` works.

`FileSelector` defaults to the first globbed path

---

examples/user_guide/Dependencies_and_Watchers.ipynb
examples/user_guide/Parameters.ipynb
param/parameterized.py
tests/testdeprecations.py
tests/testparameterizedobject.py
tests/testwatch.py

Closes https://github.com/holoviz/param/issues/780
- `.param.watchers` no longer return the transient dict of watchers (breaking change)
- instead it returns what used to be returned by `_param_watchers`
- `_param_watchers` has been turned into a deprecated property
I just ran the unit test suite of Panel with this branch checked out without any problem.

Deprecate `._param_watchers` in favor of `.param.watchers`

---

param/__init__.py
tests/testfileselector.py

Fixes https://github.com/holoviz/param/issues/139

FileSelector: ensure path separators are consistent on Windows

---

param/_utils.py
param/parameterized.py
tests/testparameterizedobject.py
tests/testparameterizedrepr.py

Fixes https://github.com/holoviz/param/issues/371 by:
1. removing the automatically inferred *docstring signature* (e.g. `params(x=Number, name=String)`) as IPython would no longer leverage it for parameter autocompletion (as noted in the issue) and because it was wrong when the class was having an `__init__` method with a signature different than `__init__(self, **params)`
2. implementing `Parameterized.__signature__` as a class property that returns a `Signature` built from the class Parameters, **only** when the class (or its superclasses) doesn't implement an `__init__` method that is different than the default one `__init__(self, **params)`.
Somewhat surprisingly 2) seemed to have broken only a few tests in Panel and none in HoloViews. The two unit tests that broke in Panel are …

Remove inferred docstring signature and add basic __signature__ support

---

param/parameterized.py
tests/testparameterizedobject.py

This PR re-validates the Parameter default if you override the Parameter type on a subclass to a more specific or completely different type. Technically it should also re-validate when certain slot values change but I wanted to start with a more limited change.

Re-validate default when Parameter type changes on subclass

---

param/parameterized.py
tests/testparamdepends.py

The dynamic resolution of dependencies loosened the validation for dependencies. However this was only intended to allow dynamic dependency resolution of the leafs or branches of nested dependencies, i.e. the root of a nested dependency has to be declared. This adds validation to ensure that the root dependency can be resolved and adds an error otherwise.

Validate dependencies in constructor

---

param/__init__.py
param/_utils.py
param/parameterized.py
tests/testaddparameter.py
tests/testbooleanparam.py
tests/testbytesparam.py
tests/testcalendardateparam.py
tests/testcalendardaterangeparam.py
tests/testcallable.py
tests/testclassselector.py
tests/testcolorparameter.py
tests/testdateparam.py
tests/testdaterangeparam.py
tests/testlist.py
tests/testlistselector.py
tests/testnumberparameter.py
tests/testobjectselector.py
tests/testpandas.py
tests/testparameterizedobject.py
tests/testpathparam.py
tests/testrangeparameter.py
tests/testselector.py
tests/teststringparam.py
tests/testtupleparam.py
tests/testutils.py

The error messages raised by Parameters are pretty inconsistent and often lack context.
For now with this PR I'm just seeking feedback on a utility I've added that builds a message supposed to prefix most of (if not all) the errors raised by Parameters. I've just adapted the type validation performed by `Number` to show the error messages emitted in various situations:
(I'd hope to get this into the 2.0 release.)

Improve Parameter error messages

---

numbergen/__init__.py
param/__init__.py
tests/testlistselector.py

Fixes #807. Makes _update_state from #794 aware of list-type defaults so that it adds the items on the list to the objects, not the entire default value as a sublist. This change does seem to be successful, avoiding `objects=1, 2, 3, [1, 2]]`:
Regarding the discussion in #807:
> Actually I'm even thinking that https://github.com/holoviz/param/issues/693 is a silly usage of Param and I'm no longer sure we should "fix" it. That's the example I shared in https://github.com/holoviz/param/issues/693, why would you not include 3 in the objects?? On top of that check_on_set is pretty clearly worded with on_set and not on_init.
After looking into it I agree. We definitely shouldn't do any extra work to make this code legal:
```python
import param
class P(param.Parameterized):
s = …
```

Listselectordefault

---

param/__init__.py
tests/testfileselector.py
tests/testmultifileselector.py

Fixes https://github.com/holoviz/param/issues/545
Supersedes https://github.com/holoviz/param/pull/546
The issue stated about `FileSelector`:
> FileSelector behaves like Selector and should as such set its value to the first item of objects, objects being the result of a glob on path.
This has been addressed in https://github.com/holoviz/param/pull/801.
About `MultiFileSelector`:
> Also the docs currently state that the default value is all of the matched files, but in practice it's None.
While that's what the docs say, the behavior of `ListSelector` from which `MultiFileSelector` inherits is for `default` to be `None` so I'm not sure we should make this change without also updating `ListSelector`. Also, Panel maps the `MultiFileSelector` parameter to the …

Updating `path` on a `File/MultiFileSelector` Parameter updates `objects`

---

param/__init__.py

FileSelector and MultiFileSelector have logic to compute a list of objects from the files on a file system, which they then pass into their Selector superclass as if it had been provided in the constructor. Probably from not being updated when ListProxy was added and `objects` became a property, what ended up being passed to the superclass was a ListProxy, which the superclass then dutifully stored into the _objects attribute behind the objects property. The result was that these two classes ended up with a ListProxy of a ListProxy of a list, which is surely not what was intended. This PR passes the _objects list to the superclass as I believe was intended. The filenames are a plain list, not a dictionary, so the `names` portion of the property that's used by ListProxy isn't needed.
The …

Avoid storing ListProxy in *FileSelector

---

param/__init__.py
param/_utils.py
param/parameterized.py
tests/testparameterizedobject.py
tests/testselector.py
tests/testutils.py

Fixes https://github.com/holoviz/param/issues/793.
Fixes https://github.com/holoviz/param/issues/746.
Adds shallow copying of mutable slot values when instantiating Parameter objects or inheriting values for slots. Shallow copying is only done when `per_instance` is `True` (the default); if you don't want such copying you can share both Parameter instances and mutable slot values by setting `per_instance=False`.
```python
import param
p = param.Selector(objects=[1, 2], check_on_set=False)
class B(A):
p = param.Selector(default=2)
b = B()
b.p = 3
print(A.param.p.objects, B.param.p.objects, b.param.p.objects)
```
(previously A's objects list was also [1, 2, 3]; now fixed to be [1, 2])
There are various issues still, as listed below.
Needs a test capturing the …

Shallow-copy mutable containers in slot values 

---

param/__init__.py
tests/testcalendardaterangeparam.py
tests/testdaterangeparam.py
tests/testrangeparameter.py

Fixes https://github.com/holoviz/param/issues/660

Validate the type of `bounds` and `softbounds` attributes for Range parameter types

---

param/parameterized.py
tests/testparameterizedobject.py
tests/testpathparam.py

This PR adds validation when overriding slot values on a Parameter in a subclass. It does this by checking if a superclass defines a slot value and if that slot value is overridden by the subclass. It attempts to minimize the number of actual lookups by aborting early if we already know that re-validation has to happen and by skipping checks on various slot values which do not affect validation.
Fixes https://github.com/holoviz/param/issues/714

Ensure Parameter re-validates default if slot changes

---

param/parameterized.py
tests/testwatch.py

In https://github.com/holoviz/param/pull/826 we discovered some weird logic that was copying over watchers from class to instance parameters. After discussing this we all agreed this does not make sense, this is because slots are not shared between class and instance parameters and therefore it does not make sense that an instance parameter would inherit the watchers from a completely different `Parameter` instance. Worse yet, once an instance was created the watcher would be removed from the class which means that modifying the class `Parameter` slot value would no longer trigger the watcher.
The correct behavior is actually quite simple, watchers should not be copied over, instead the `Parameter` slot watchers should be reset when the instance parameter is created. This ensure that …

Ensure class watchers are not inherited by instance parameter

---

param/parameterized.py
tests/testparameterizedrepr.py

Fixes https://github.com/holoviz/param/issues/822
This regression was due to having moved `_repr_html_` from `Parameterized` to `Parameters`. I've added a basic test what would have caught it (cherry picked https://github.com/holoviz/param/pull/821/commits/bcb8a4c4a6479dcd70e59778ef3d7045b806adae to avoid some warnings).
```python
import param
class Sub(param.Parameterized):
xsub = param.Parameter()
class P(param.Parameterized):
constant = param.Parameter(constant=True)
readonly = param.Parameter(readonly=True)
allow_None = param.Parameter(1, allow_None=False)
bounds = param.Number(bounds=(-10, 10))
objects_list = param.Selector(objects=[1, 2])
objects_dict = param.Selector(objects=dict(a=1, b=2))
sub = param.ClassSelector(default=Sub(xsub=1), class_=Sub)
P().param
```

Fix HTML repr for Parameterized subobjects

---

param/parameterized.py
tests/testparameterizedobject.py

We are finding that some users do not correctly call `super().__init__()` at all or perform actions that are not safe before they call it. To guide more users to the correct behavior and avoid undefined/weird behavior this PR adds some validations and errors to certain methods on the `.param` namespace.

Ensure operations that are unsafe during instance initialization raise errors

---

param/parameterized.py
tests/testdeprecations.py
tests/testparameterizedobject.py

https://github.com/holoviz/param/pull/834 added a few checks for preventing users from calling unsafe methods before a Parameterized instance has fully been initialized. This broke the hvPlot Explorer and is likely to break quite a lot of code, in particular for users who aren't so aware of the importance and meaning of calling `super().__init__()`. I propose with this PR to downgrade these errors to warnings, to FutureWarnings in particular that will always be surfaced to users, as they're likely to be shooting themselves in the foot and we want to let them know about it.

Warn instead or raise an error when doing an action before Parameterized initialization

---

param/parameterized.py

An attempt at mitigating some of the performance regressions associated with Param 2.0

Mitigating performance regressions in 2.0

---

param/parameterized.py

Started looking at `.param` and noticed this really bizarre (and pointless) double indirection when accessing variables on the `Parameters` object. There's a bunch of cases where instead of accessing methods directly on the `Parameters` object we go through this two-level indirect attribute access that just to get back to the same object, i.e. `self_.self_or_cls.param._TRIGGER` simplifies to just `self_._TRIGGER`.
In fact this is so silly that fixing it gives a 10% performance boost for a bunch of common operations:

Fix multi-level indirection in Parameters access

---

param/reactive.py
tests/testreactive.py

Previously internal callbacks (with `precedence=-1`) could run before the `reactive` object was fully invalidated causing the cached value to be returned. We now run invalidation callbacks with the `precedence=-1` ensuring that they run first.

Fix issue with precedence of reactive invalidation callback

---

doc/user_guide/Reactive_Expressions.ipynb

I think this will take several iterations, but I've tried to tease out a better motivating introductory section without making too many changes. @philippjfr , please review and see if it's going in a direction you're happy with; feel free to close if not.
I suspect that it's still trying to be too ambitious, and that we shouldn't immediately dive in trying to change the dataframe itself, because that's an advanced topic using `bind`, while if we simply make the dataframe and some values reactive, I think the user will be able to see how it works much better. If I get a chance I'll try that out, but wanted you to have this before I went to bed in case you work on it tomorrow.
I also think the example still isn't that great without widgets. I do like what it does for the loop I put in there …

Updated reactive docs

---

param/__init__.py
param/depends.py
param/ipython.py
param/parameterized.py
param/reactive.py
tests/testrefs.py

This PR brings an exceptionally useful feature that we have had in Panel since 1.2 to Param. Specifically it allows passing Parameter references (i.e. Parameter objects, reactive functions and expressions) as a parameter value and then automatically mirrors the value of the reference, e.g.:
```python
class Parameters(param.Parameterized):
string = param.String(default="string", allow_refs=True)
p = Parameters()
p2 = Parameters(string=p.param.string)
assert p.string == p2.string
p.string = 'new_string'
assert p2.string == 'new_string'
```
This is much, much easier than setting up callbacks and together with the addition of reactive functions and expressions makes it super easy to set up parameters that depend on some other dynamically computed values. The implementation here is fully …

Implement support for allowing Parameter references

---

param/parameterized.py

The `resolve_ref` utility was not handling methods decorated with dependencies correctly.

Allow resolving references on Parameterized method

---

param/reactive.py
tests/testreactive.py

The previous implementation was trying to be too clever. This implementation is simpler but achieves the same thing.

Fix implementation of rx.__iter__

---

param/parameterized.py
tests/testrefs.py

The `resolve_ref` function did not correctly resolve dependencies on subobjects, e.g.:
```python
@param.depends('subobject.string')
def string(self):
return self.subobject.string + '!'
```

Ensure nested parameter dependencies are resolved as references

---

doc/user_guide/Reactive_Expressions.ipynb
param/reactive.py
tests/testreactive.py
tests/testrefs.py

Overall this seems much cleaner. Some consequences:
- We no longer allow setting the value of a non-root node of a reactive expression, i.e. `(rx(1) + 1).value = 2` is invalid. This was always what was confusing and made naming this difficult.
- We now automatically gain support for increment (i.e. `.rx.value +=`) and other arithmetic/boolean assignment operators

Replace .rx.resolve and .rx.set_input with .rx.value property

---

param/parameterized.py
tests/testdeprecations.py
tests/testparameterizedobject.py

As discussed today, we have decided to just warn for now on failed `default` validation while inheriting Parameter attributes in a hierarchy of classes. The reasoning being that raising an error on failed validation would be too disruptive, as it would break users code on import and would probably be a painful process to update, going one Parameter after another. I have attempted to give as much context as possible (without resorting to `inspect` though) in the error message, which can be seen in the tests. I have chosen to emit a `ParamFutureWarning` that is unconditionally displayed, we really want users to fix their code as soon as they see this warning.

Only warn on failed default validation while inheriting Parameter attributes

---

param/display.py

I would get this error when running `panel serve --autoreload` and changing an imported module.

Don't raise warning if accessor is from same module

---

param/reactive.py
tests/testreactive.py

Fixes https://github.com/holoviz/param/issues/866

Avoid multiple unncessary evaluations when making rx clone

---

param/parameterized.py
param/parameters.py
tests/testlistselector.py

Fixes https://github.com/holoviz/param/issues/872
I also found a pretty bad bug in `_instantiate_param_obj` where we were looping only through the `__slots__` defined on the Parameter class, ignoring the ones it inherits. Easy mistake, `kls.__slots__` should really return all the slots! This bug led `ListSelector._objects` being shared between a Parameterized class and instance, since the `_objects` slot is declared in a parent class.
```diff
-    for s in p.__class__.__slots__:
+    for s in p.__class__._all_slots_:
v = getattr(p, s)
if _is_mutable_container(v) and s != "default":
setattr(p, s, copy.copy(v))
```
I also made sure that setting `None` with `check_on_set=False` and `allow_None=True` doesn't add `None` to the objects.

Fix regression in ListSelector with `check_on_set=False`

---

param/parameterized.py

Fixes https://github.com/holoviz/panel/issues/5730

Copy explicit_no_refs from ClassPrivate to InstancePrivate

---

pyproject.toml
tests/testfiledeserialization.py

It is just a wrapper for `pyarrow.feather`, which we can use directly.

Drop the feather-format test dependency

---

pyproject.toml

Tested in a clean git checkout:
```
python3 -m build
python3 -m wheel unpack dist/param-*.whl
find param-*/doc/
```
```
find: ‘param-*/doc/’: No such file or directory
```

Do not install “doc” in site-packages (fix #877)

---

pyproject.toml

Enables one additional test.
https://github.com/holoviz/param/blob/b6a285b7205a869b5677b8571fd54c2a5ccc8709/tests/testfiledeserialization.py#L63-L66
https://github.com/holoviz/param/blob/b6a285b7205a869b5677b8571fd54c2a5ccc8709/tests/testfiledeserialization.py#L76
https://github.com/holoviz/param/blob/b6a285b7205a869b5677b8571fd54c2a5ccc8709/tests/testfiledeserialization.py#L205-L213

Add “tables” to the tests-deser extra

---

param/parameterized.py

By adding forgotten underscores when moving them to the `.param` namespace. They're not tested at all.

Fix `_state_push` and `_state_pop`

---

param/__init__.py

I noticed `setuptools_scm` took too long to load:
`python -X importtime -c "import param" 2> log.txt && tuna log.txt`

Don't use setuptools_scm if .git does not exists

---

param/version.py
tests/testversion.py

`subprocess.CREATE_NO_WINDOW` is a Windows constant so it fails on other platforms: https://docs.python.org/3/library/subprocess.html#windows-constants.
Also adding a simple test that would have caught that.

Set `creationflags` on Windows only

---

param/_utils.py
tests/testutils.py

We've observed that `inspect.iscoroutinefunction` doesn't return the same output of different versions of Python 3.10 when the function is a `functools.partial`. We make sure that param's `iscoroutinefunction` (that covers async generators too) unpacks partials before checking if they wrap a coroutine/async generator or not.

Unpack partial in iscoroutinefunction

---

benchmarks/benchmarks/benchmarks.py
param/parameterized.py

No reason why the have to call `.objects` to get the list of parameters and also no reason we have check all parameters.

Minor optimizations in hot codepaths accessing class parameters

---

param/__init__.py

Fixes #897
I think `importlib.metadata import version; __version__ = version('<package_name>')` is now the recommended way to get the version of an installed package. Except that I guess it makes things a bit slower and I don't know how stable that is. So I chose to still rely on trying first to get the version from `_version.py` (automatically created by hatch-vcs/setuptools-scm) and only then, if it fails like in #897, to try to get it using `importlib`.

Fix building with setuptools-scm<7

---

tests/testfiledeserialization.py

Pandas 3.0 will not allow calling `to_hdf` with positional arguments (except the first one). This only affects the test suite.

Tests: compatibility with Pandas 3.0

---

param/parameterized.py
tests/testparameterizedobject.py
tests/testrefs.py

This PR does two things:
1. Ensures that `.param.update` restores the references when exiting the context
2. Allows `.param.update` to accept an argument AND kwargs, just like `dict.update`.
Fixes https://github.com/holoviz/param/issues/914

Ensure that .param.update context manager restore refs

---

param/reactive.py
tests/testreactive.py

Fixes https://github.com/holoviz/param/issues/913

Add support for async watcher to rx

---

param/parameterized.py
param/reactive.py
tests/testreactive.py

I'm a little afraid at how "meta" this operation is but it allows doing some things which aren't otherwise possible with `.rx` (or rather extremely complicated). Specifically this allows writing expressions that themselves contain references and then recursively resolves them. The case where I encountered the need for this is a Panel ToDo app.
Let us say we have a layout of tasks:
```python
tasks = pn.Column(task1, task2)
```
Each task is structured like this:
```python
task = Row(Checkbox(), Markdown())
```
Now I can write a simple expression to gather up all checkboxes:
```python
checkboxes = tasks.param.objects.rx().rx.map(lambda task: task[0])
```
And if want to get the number of completed tasks I could do:
```python
sum(checkboxes.rx.map(lambda w: w.value))
```
Unfortunately this …

Make it possible to resolve rx expressions recursively

---

param/_utils.py
param/parameterized.py
tests/testdeprecations.py
tests/testsignatures.py
tests/testwatch.py

Bumping the warnings from `PendingDeprecationWarning` to `DeprecationWarning`.
Also, turning a `FutureWarning` to a `ParamFutureWarning` for the sake of consistency.

Warn with DeprecationWarnings when instantiating Parameters with extra positional arguments

---

param/reactive.py
tests/testreactive.py
tests/utils.py

We already support using asynchronous and generator functions as inputs to a reactive expression but until now we did not handle them when you use them as an input to an operation that is performed on the data. This meant that `.rx.pipe` and `.rx.map` would simply return the coroutine or generator as the value instead of evaluating it lazily.
Here we add support for these by scheduling the task on the event loop and then triggering an event when the function evaluates. Internally this is achieved by creating a `Trigger` which is added as one of the dependencies of the reactive expression such as that any consumer of the expression (whether Panel, the display hook or anything else) is notified when the async function or generator yields a new value.
In testing this I also found an …

Add support for async and generator functions in rx.pipe

---

doc/releases.md

I plan to release in the morning.
Date: 2024-01-22
This minor release focuses on improving reactive expressions and support for asynchronous (and synchronous) generators. Many thanks to @maximelt, @Hoxbro and @philippjfr for their continued maintenance and development efforts.
- Improvements for synchronous and asychronous generators ([#908](https://github.com/holoviz/param/pull/908))
- Additions to the .rx namespace including `and_`, `bool`, `map`, `not_`, `or_`, `updating` ([#906](https://github.com/holoviz/param/pull/906))
- Add support for asynchronous watcher to `rx` ([#917](https://github.com/holoviz/param/pull/917))
- Make it possible to resolve rx expressions recursively with `.rx.resolve` ([#918](https://github.com/holoviz/param/pull/918))
- Add support for async and generator …

Add CHANGELOG 2.1.0

---

param/parameterized.py
tests/testreactive.py

@Hoxbro Please test and if possible add your test case.

Ensure refs can be updated by watcher of the same parameter

---

param/parameterized.py
tests/testparameterizedobject.py

Fixes https://github.com/holoviz/param/issues/937
Logging this change in case we agree on the suggested change in the issue.

Only override the name of a Parameterized instance on Parameter instantiation when `instantiate=True`

---

doc/user_guide/Reactive_Expressions.ipynb

Unsure if I should have a separate sentence mentioning `Reactive expressions are natively supported in Panel` or just link it like in this PR.

Point to Panel RX

---

param/parameterized.py
param/reactive.py
tests/testreactive.py
tests/testrefs.py

Attempts to fix https://github.com/holoviz/param/issues/940
Which can be reproduced with:
```python
import param
start = param.rx(1)
end = param.rx(10)
l = list(range(20))
lrx = param.rx(l)
sx = lrx[start:end]
print(sx.rx.value)  # required to reproduce
start.rx.value = 4
print(sx.rx.value)  # [1, 2, ...], not [4, 5, ...] ! 
```
I think that the reactive expressions of the `start:end` *slice* passed to `__getitem__` were not resolved, which means that no watcher was set to invalidate the expression when `start` is updated. Resolving references recursively fixed the issue and broke no other test, but well, it might be a big hammer 🤔 Anyhow, I've also added another similar test that would have failed without this change, this time with a *tuple* containing reactive expressions passed to …

Recursively resolve references on args and kwargs passed to an reactive operation

---

param/reactive.py
tests/testreactive.py

Previously accessors weren't resolved correctly.

Ensure rx._callback resolves accessors

---

doc/releases.md

Date: 2024-06-25
This minor release contains bug fixes for reactive expressions and a few minor documentation improvements. Thanks to @jrycw for their first contribution! And to @ahuang11, @maximelt, and @philippjfr for their continued maintenance and development efforts.
Bug fixes:
- Ensure `rx._callback` resolves accessors ([#949](https://github.com/holoviz/param/pull/949))
- Ensure refs can be updated by watcher of the same parameter ([#929](https://github.com/holoviz/param/pull/929))
- Recursively resolve references on args and kwargs passed to a reactive operation ([#944](https://github.com/holoviz/param/pull/944))
- Only override the name of a Parameterized instance on Parameter instantiation when `instantiate=True` ([#938](https://github.com/holoviz/param/pull/938))
Documentation: …

Add release notes for v2.1.1

---

param/_utils.py
param/depends.py

It took some tinkering but I finally have this working. Addresses https://github.com/holoviz/param/issues/958
@MarcSkovMadsen @philippjfr 
Results:
```
>> mypy param/_utils.py --follow-imports=silent
Success: no issues found in 1 source file
```
```
>> mypy param/depends.py --follow-imports=silent
param/depends.py:142: error: Item "str" of "Parameter | str" has no attribute "owner"  [union-attr]
param/depends.py:144: error: Item "str" of "Parameter | str" has no attribute "owner"  [union-attr]
param/depends.py:144: error: Item "str" of "Parameter | str" has no attribute "name"  [union-attr]
```

Annotate depends and accept_arguments decorators

---

param/parameterized.py

Currently the `_ParameterBase.__init_subclass__` method does not forward to the method on its superclass, so any other base classes in the MRO do not have a chance to perform any necessary subclass initialization steps. This PR adds the missing call.
This is particular relevant when defining a `Parameter` subclass with generic type parameters by inheriting from `typing.Generic` (or equivalently by using the new generics syntax added in Python 3.12). Inheriting from `typing.Generic[T]` where `T` is a `typing.TypeVar` typically allows a class to be parameterized by a concrete type, but this does not work when `_ParameterBase` is in the MRO since the `__init_subclass__` call is not properly propagated up the MRO.
The following example raises an `AttributeError` in the current `param` …

Added missing `super().__init_subclass__` call in `_ParameterBase.__init_subclass__`

---

tests/testreactive.py

The weekly scheduled job has been failing intermittently over the last months due to one reactive test failing on Windows.
```
================================== FAILURES ===================================
_________________________ test_reactive_gen_with_dep __________________________
async def test_reactive_gen_with_dep():
def gen(i):
yield i+1
time.sleep(0.05)
yield i+2
irx = rx(0)
rxgen = rx(bind(gen, irx))
assert rxgen.rx.value is param.Undefined
await asyncio.sleep(0.04)
assert rxgen.rx.value == 1
irx.rx.value = 3
await asyncio.sleep(0.04)
>       assert rxgen.rx.value == 4
E       assert 5 == 4
E        +  where 5 = <param.reactive.reactive_ops object at 0x0000020D4E3FE450>.value
E        +    where <param.reactive.reactive_ops object at 0x0000020D4E3FE450> = <param.reactive.rx …
```

Attempt to fix one reactive test failing intermittently on Windows

---

param/_utils.py
param/parameterized.py
param/parameters.py
tests/testimports.py
tests/testutils.py

The changes made in this PR are not to directly import non-essential imports (numpy in param) but to only check for the case when the user has already imported them.
This comes down to two things:
1) For param, this is to "hide" numpy imports in functions or generators. This is strictly not necessary, but people check import time with `python -X importtime -c 'import param'`, and because we do an actual import of numpy, we are heavily penalized by it. The random modules (numpy and stdlib) also seem unnecessary to import, only to use the import for not outputting anything with `pprint`. 
2) The second part involves using a new decorator, which overloads `isinstance` and `issubclass` and still makes it function like a generator with and without calling it. This approach can be used in our …

refactor: Don’t directly import numpy and add `gen_types` decorator

---

doc/upgrade_guide.md
param/_utils.py
param/parameterized.py
param/parameters.py
tests/testparameterizedobject.py

I think this function does exactly what a normal `dict` does if the first argument is a dict.

refactor: Remove `_dict_update`

---

numbergen/__init__.py
param/_utils.py
param/depends.py
param/ipython.py
param/parameterized.py
param/parameters.py
param/reactive.py
param/serializer.py
param/version.py
pyproject.toml
tests/testcompositeparams.py
tests/testdynamicparams.py
tests/testparameterizedobject.py
tests/utils.py

Builds on #977. So review that one first.
The only thing I've touched is in pyproject.toml. The rest is auto fixed by Ruff when I run `ruff check`.

Add Ruff D rule

---

doc/reference/param/generated/param.rx.rst
doc/reference/param/reactive.md

Somehow https://github.com/holoviz/param/pull/977 by adding the `rx` property broke the autosummary API doc build of the `rx` class. I've made this change and pushed the generated file as a workaround to unblock the release.
```
.. autosummary::
~rx.__init__  # I've removed that line!
~rx.register_accessor
~rx.register_display_handler
~rx.register_method_handler
```

Fix generating the API doc

---

numbergen/__init__.py
param/_utils.py
param/parameters.py
pixi.toml
pyproject.toml
tests/testtimedependent.py

Closes https://github.com/holoviz/param/issues/661
https://github.com/holoviz/param/pull/971 added `gmpy2` in the `pixi.toml` file instead of `gmpy`, which are two different projects (the former being maintained while the latter hasn't received an update since 2013). The test suite wasn't updated accordingly so the gmpy-related tests were all skipped (attempting to import `gmpy` instead of `gmpy2`).
This MR lets us "officially" drop support of the `gmpy` Python library (which probably no one used with Param?) in favor of `gmpy2`.
I'm not entirely sure Param should keep supporting that but ensuring the test suite passes with gmpy2 wasn't too much work. I'd be okay if someone pushes to deprecate it.

Drop gmpy support in favor of gmpy2

---

.github/workflows/test.yaml
doc/developer_guide.md
pixi.toml
pyproject.toml

Closes https://github.com/holoviz/param/issues/1028
EDIT:
Ok the CI is green now. I've removed a few dependencies we used to run the PyPy tests with (e.g. pandas) as they were slow to build (7-10 minutes).

Update the CI to test with PyPy 3.10

---

doc/reference/param/parameterized_helpers.md
param/_utils.py
tests/testutils.py

Somewhat related to https://github.com/holoviz/param/issues/651, the idea being to steer users towards `descendents` instead of `concrete_descendents` (to deprecate it ultimately but it'll take a little while as it's used in a lot of holoviz code bases).

Add concrete keyword to descendents

---

doc/reference/deprecations.md
doc/reference/index.md

Re-adding this page with a list of the current deprecations (originally added in https://github.com/holoviz/param/pull/922 but closed) as I find myself returning again and again to it. It's very useful to track when a warning was introduced and bumped. As discussed in the old PR, whether it's useful for users or not is questionable, but it's very useful to me at least, and might be useful for someone out there (all the more so as we don't have docs versioning in place).
I've also added a table that lists the removed APIs (didn't go back in time past 2.2.0) as this table is easy to maintain, just moving the row from the table of deprecated APIs to this table, and adding the version in which the API was removed.
EDIT after the docs build:

doc: add a page that lists the deprecated and removed APIs

---

doc/user_guide/Parameter_Types.ipynb
param/parameters.py
tests/testlist.py

Closes https://github.com/holoviz/param/issues/868

Add is_instance attribute to the List Parameter

---

param/parameterized.py
tests/testparameterizedobject.py

Fixes https://github.com/holoviz/param/issues/1001
Let's have a good look at the downstream tests before releasing 2.3.0, this is a nasty bug.

Ensure constant attribute is inherited

---

param/reactive.py
tests/testreactive.py

Closes https://github.com/holoviz/param/issues/954
The suggestion in the issue was:
> I believe we can't implement `__len__` reactively, but can't we provide a better error message in this case? E.g. it seems like we could print a warning saying that the value returned won't be reactive (and what to do instead (`.rx.len()`), and then return the non-reactive length.
I am not in favor of emitting a warning and returning the non-reactive length as this sets a bit of a weird precedent (we could do the same for other parts of the Python data model we can't proxy). Instead with this PR a `TypeError` is raised with a more explicit message. Note that if in the future we decide to warn and return the non-reactive length, that PR makes it still possible.
```
TypeError: len(<rx_obj>) is not …
```

Better error when calling len() on a reactive expression

---

doc/user_guide/Parameters.ipynb

Added a missing word, and added that the numbering in name starts at 00000 for instances. If there is a reference known to the source code / lines where this is defined, I will add it to the doc.

Update Parameters.ipynb to add missing word.

---

param/_utils.py
param/parameterized.py
param/reactive.py
tests/testimports.py

This PR improves the import time by postponing the import of `asyncio`, `logging`, and `html`. And also not updating signatures if not inside a IPython environment. 
Generated with `python -X importtime -c 'import param' 2> tuna.log && tuna tuna.log`. Some notes only focus on the param and ignore the `param.version` time; also, the measurement is not exact (see hyperfine) and needs warmup time after a branch change. 
Main (https://github.com/holoviz/param/commit/9ff6a9f9c7c36cf2e760f18807d7c538bb42e255):
After removing asyncio (https://github.com/holoviz/param/pull/1037/commits/5a63a9e5f5027f31a10a6f2e7ef40485ec1720b5):
`+` After removing logging and HTML (https://github.com/holoviz/param/pull/1037/commits/3d4885b4a30b8dfb3689a56421fbf510087e4752)
`+` Without updating signature in …

perf: Improve import time by lazy import "slow" modules

---

doc/reference/deprecations.md
param/parameterized.py
tests/testdeprecations.py

Closes #1004 
In some way this could have been removed directly because of the `assert what == 'value'` statement but assert statements can be ignored when running python with the `-O` flag. Directly a FutureWarning as I don't expect many users to be in the situation where they set `what` and run python with `-O`.

Deprecate the keyword what of `.param.watch_values`

---

doc/user_guide/Dependencies_and_Watchers.ipynb
param/parameterized.py
tests/testwatch.py

Resolves https://github.com/holoviz/param/issues/1003
By raising `ValueError` when trying to remove an already removed/never registered watcher.

`unwatch` no longer logs a warning and idempotent behavior clarified
