holoviz/param

- param/__init__.py
- param/parameterized.py
Resubmission of PR https://github.com/ioam/param/pull/76, which was accidentally merged (I've undone that now).
> Added Tuple and AllowsNone Parameters

- param/version.py
Simple change allowing the commit_count can now be set via the ``param.Version`` constructor.
> Extended Version constructor

- param/__init__.py
Fixes https://github.com/ioam/param/issues/137.
> Fixed setting of ListSelector and MultiFileSelector in paramnb

- param/__init__.py
* Color: Expects an RGB hex string with optional # prefix
* Date: Has to be datetime or np.datetime64 type
The Date parameter could support bounds like Number but I'm not sure how important that is.
> Added Color, Date and Range parameters

- param/__init__.py
> Fixed Color value check

- tests/testcolorparameter.py
- tests/testdateparam.py
- tests/testrangeparameter.py
> Added tests for Color, Date and Range params

- param/__init__.py
- tests/testdefaults.py
Also added tests for all parameter subclass default values.
> Fixed incorrect default value for param.Integer (#151).

- tests/testdefaults.py
> Skip test of Array parameter when numpy not available.

- numbergen/__init__.py
- param/__init__.py
- setup.cfg
Presumably won't catch cases like in #208, but might catch some others...we'll see.
> Enable more flake8 checks.

- param/__init__.py
- tests/testlistselector.py
Fixes ListSelector.compute_default() and adds tests for ListSelector.
> ListSelector tests and fix for compute_default

- .travis.yml
- conda.recipe/meta.yaml
- setup.cfg
- setup.py
- tox.ini
* specify test dependencies in setup.py
* simplify running of test tools
* reduce duplication of packaging metadata
> Simplifications related to packaging and testing.

- param/version.py
* Allow develop_install to work (https://github.com/ioam/autover/pull/41)
* Failed to report 'dirty' for commit count of 0 (https://github.com/ioam/autover/pull/44)
> Update version.py from autover for various fixes

- param/version.py
> Update version.py from autover to get setup.py functions.

- param/parameterized.py
@philippjfr, does this cover what you need?
Also, could you comment on the 4 TODOs shown below?
> Dependencies: add unwatch()

- param/parameterized.py
- tests/API1/testwatch.py
At the time of creation, this PR only implements some (hopefully!) non-controversial improvements. The rest of it will implement parameter subset semantics (we called this 'option 3') for batching.
> Implementation of batched watching

- param/parameterized.py
- tests/API1/testwatch.py
Currently work in progress PR to implement triggering. Doesn't yet handle `what` (assumed to be `'value'` by default).
> Implemented trigger method to trigger watchers at any time

- .travis.yml
- param/__init__.py
- setup.py
- tests/API0/testdefaults.py
- tests/API1/testdefaults.py
- tests/API1/testpandas.py
- tox.ini
Currently WIP. As of the first commit, these two parameter types follow the implementation of `param.Array` which is just syntactic sugar for a `ClassSelector`. I'll now be adding options for additional validation.
> Added pandas DataFrame and Series parameter types

- param/__init__.py
- param/parameterized.py
Implements https://github.com/pyviz/param/issues/300
> Refactored Parameter validation

- param/parameterized.py
* Fixes issue with batch watch flag not being restored on exceptions
* Fixes issues with Parameterized.params not returning instance parameters because it is a classmethod
> Minor bug fixes

- param/parameterized.py
- tests/API1/testparamoutput.py
> Resolve annotated outputs using MRO

- param/__init__.py
- param/parameterized.py
- tests/API1/testparamunion.py
Supersedes https://github.com/pyviz/param/pull/308
> No longer use root logger

- .travis.yml
Also simplifying nbsite syntax
> Updating dev website to use pyviz-dev

- README.rst
> Try to fix CI problems

- examples/About.ipynb
> Updated About page to be consistent with other projects

- param/parameterized.py
Title says it all. Ready to review/merge.
> Removed outdated warning message

- examples/index.ipynb
Small PR removing the support section
> Removing the Support section from the Param home page

- examples/About.ipynb
@jlstevens @philippjfr 
I updated the notebook for the Param About section, let me know what you think.
> update Param about section

- param/__init__.py
- tests/API1/testwatch.py
I have learnt about param's watching mechanism by inspecting testwatch.py
Here are a few tests and assertions i added to further understand it, i thought they might be useful to others as well.
I also removed some blank lines to satisfy PEP8 recommandation (and remove IDE code inspection highlights)
> added some tests and assertions that in testwatch

- param/parameterized.py
The `param.depends` decorator was previously registering a separate watch callback for each parameter it was watching. This PR ensures that `param.depends` registers a single callback for each parameterized object being depended on.
> Batch param.depends

- doc/conf.py
@jlstevens @philippjfr 
I added the Google Analytics ID to the conf.py file.
> Adding the Google Analytics ID

- param/parameterized.py
3 spaces?! It took me a while to realize why my editor was constantly trying to use 3 spaces. It's like you're trying to illustrate why we should just auto-format the code and be done with this kind of thing ;)
> Fix indentation

- param/parameterized.py
- tests/API1/testwatch.py
Supersedes https://github.com/holoviz/param/pull/430
> Fix discard_events decorator

- param/parameterized.py
Allows declaring an asynchronous executor on `param.parameterized.async_executor` which allows using async functions (i.e. coroutines) as `.param.watch` callbacks and will schedule them on the event loop (Tornado or asyncio). As an example, Panel will register these executors depending on whether it is running on Bokeh server or the notebook:
```python
param.parameterized.async_executor = IOLoop.current().add_callback
```
```python
param.parameterized.async_executor = pn.state.curdoc.add_next_tick_callback
```
> Declare asynchronous executor

- .github/workflows/docs.yml
- doc/index.rst
Directive will be respected for latest nbsite.
> Disabling interactivity warning on homepage

- param/__init__.py
> Adds step to Range

- param/__init__.py
- tests/API0/testcolorparameter.py
- tests/API1/testcolorparameter.py
> Allow named colors on param.Color

- param/parameterized.py
Fixes https://github.com/holoviz/param/issues/148
> Fix bug related to instantiate on param.defaults

- param/__init__.py
- tests/API1/testpandas.py
Fixes https://github.com/holoviz/param/issues/405
> Fix allow_None for param.Series and param.DataFrame

- param/ipython.py
https://github.com/holoviz/param/issues/443
> Sort docstring by precedence

- param/__init__.py
- param/parameterized.py
- tests/API0/teststringparam.py
- tests/API1/teststringparam.py
Some attempt at:
1. Improving error messages so they state what the wrong value actually was (this is not always obvious)
2. Clean up line lengths
3. Clean up of spacing between arguments.
> Improved error messages and cleaned up code

- param/parameterized.py
Deleted the Parameter._on_set implementation accidentally before merging #476.
> Fix not implemented Parameter._on_set

- param/__init__.py
Fixes https://github.com/holoviz/param/issues/490 . Also combines the two separate but identical get_soft_bounds method implementations into a module function.
> Made softbounds be bounded by the hard bounds

- param/__init__.py
PR to address very minor issues I spotted in #495 and #497
> Minor tweaks and fixes

- param/__init__.py
- tests/API0/testcalendardateparam.py
- tests/API1/testcalendardateparam.py
> Calendardate accepts date values only

- param/__init__.py
> Give Range a proper docstring

- param/__init__.py
Just did this quickly in the Github interface. I'll rely on the CI to see if I need to update the tests.
> Improve the error messages of Date and DateRange

- doc/conf.py
- setup.py
Fixes #569
And a few more improvements to the site.
> Clean up the site title

- .github/workflows/test.yaml
- tox.ini
Noticed two bad issues:
* Not actually running on Python 2 :(
* Not running on the required version on Macos
> Fix the test workflow

- param/parameterized.py
- tests/API1/testparamdepends.py
Fixes https://github.com/holoviz/param/issues/618
> Fix regression in param depends execution ordering

- .github/workflows/build.yaml
- .github/workflows/docs.yaml
- .github/workflows/test.yaml
Committed via https://github.com/asottile/all-repos
> bump setup-python action

- param/parameterized.py
Ref: https://github.com/ipython/ipython/issues/13840
> Change formatting to work around an IPython 8 bug

- .github/workflows/docs.yaml
- setup.py
This is also pinning nbsite to 0.8.0rc2.
> Build the docs on Python 3.9 and some other minor changes

- examples/user_guide/Parameter_Types.ipynb
> fix reference param module link

- .github/workflows/test.yaml
Attempting to see why CI fails... hard.
> Fix CI failures

- param/_async.py
Fixes https://github.com/holoviz/panel/issues/4237 https://github.com/holoviz/panel/issues/4261
> Fix depends async wrapper

- param/__init__.py
- tests/API1/testcolorparameter.py
Named colors should be allowed to be any case.
> Allow named colors to be any case

- param/parameterized.py
- tests/API1/testparameterizedobject.py
Reverts #691 as it broke Panel and might break other things.
> Revert #691

- doc/releases.md
> Add release notes for 1.13.0

- tests/API1/testparameterizedobject.py
To capture Param's behavior described in https://github.com/holoviz/param/issues/718
> Add a test on the behavior of class attributes

- tests/testparameterizedobject.py
Simply add some tests on the class and instance `name` values, in preparation of a PR that will touch that.
> Add tests on class and instance name

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- doc/developer_guide.md
- examples/Promo.ipynb
- examples/user_guide/Dependencies_and_Watchers.ipynb
- examples/user_guide/Dynamic_Parameters.ipynb
- examples/user_guide/How_Param_Works.ipynb
- examples/user_guide/Logging_and_Warnings.ipynb
- examples/user_guide/Outputs.ipynb
- examples/user_guide/Parameter_Types.ipynb
- examples/user_guide/ParameterizedFunctions.ipynb
- examples/user_guide/Parameters.ipynb
- examples/user_guide/Serialization_and_Persistence.ipynb
- pyproject.toml
This PR adds the classic examples tests other HoloViz projects implement, using `nbval`.
> Add examples tests

- pyproject.toml
This didn't make it into the last PR but I want to pin the released version to avoid regressions.
> Pin nbsite 0.8.0

- .pre-commit-config.yaml
- examples/user_guide/Parameter_Types.ipynb
- param/__init__.py
Fixes https://github.com/holoviz/param/issues/707
> Deprecate private or unused functions in `__init__.py`

- tests/testparameterizedobject.py
I don't know what when wrong, linters are failing on the main branch apparently?
> Run all pre-commit hooks

- doc/getting_started.md
- the class in a code block should be `B` not `ParamClass`
- link to the Param guide on Panel docs was fixed
> fix minor errors in getting started page

- examples/user_guide/Dynamic_Parameters.ipynb
> Fix spelling mistake

- param/reactive.py
On complex expressions dynamically looking up the parameters and roots was just too expensive.
> Cache reactive parameters and root

- param/reactive.py
Add arguments to `.rx.watch()` and `.rx.updating()` to emit signal while reactive expression is updating.
> Add .rx.updating()

- param/parameterized.py
- pyproject.toml
- tests/conftest.py
- tests/testrefs.py
> Fixes for resolution of explicit allow_refs=False and async functions

- param/version.py
Attempts to address https://github.com/holoviz/param/issues/875
I'm not sure how to reproduce the bug exactly, and I'm not sure this fixes it.
> version.py: new process should not create a window

- pyproject.toml
See https://github.com/holoviz/holoviews/pull/6144/files#r1510843316
> Pin pytest in test-examples

- doc/getting_started.md
- doc/user_guide/Parameter_Types.ipynb
- param/parameters.py
Fixes https://github.com/holoviz/param/issues/943
Fixes https://github.com/holoviz/param/issues/942
> Minor documentation changes

- .github/workflows/build.yaml
- .github/workflows/docs.yaml
- .github/workflows/test.yaml
- pyproject.toml
- tests/testreactive.py
Fixes https://github.com/holoviz/param/issues/907
And various minor CI updates.
> Fix test_reactive_logic_unary_ops on Python 3.12

- doc/releases.md
Who dared to misspell my GitHub handle? 😈
> Fix GH username typo in the release notes

- .github/workflows/build.yaml
- scripts/conda/build.sh
See https://github.com/holoviz/geoviews/pull/770 
And also https://github.com/conda/conda-build/releases/tag/25.1.0
> build: Small updates to build infrastructure

- doc/roadmap.md
See https://github.com/holoviz/param/issues/1047 for details.
> Update roadmap.md to correct text in first paragraph

- doc/user_guide/Parameter_Types.ipynb
See https://github.com/holoviz/param/issues/1051 for details.
> Update Parameter_Types.ipynb to fix a 404.

- doc/governance/project-docs/MEMBERS.md
Adding myself to better reflect the project's state.
> Update list of maintainers
